### ISSUE TITLE
move test_aws_credentials_validation to 'live' tests

### ISSUE THREAD

**Issue by jtriley** [jtriley/StarCluster#121]
The test_aws_credentials_validation test requires a network connection in order to run. Need to move this to a 'live' tests module that only runs when a special 'flag' has been flipped.

https://bugs.gentoo.org/show_bug.cgi?id=426528

**Comment by jtriley** [comment]
```
 * Testing of dev-python/starcluster-0.93.3 with CPython 2.7...
PYTHONPATH=build-2.7/lib nosetests --verbosity=1 -v starcluster/tests
test_aws_credentials_validation (starcluster.tests.test_cluster_validation.TestClusterValidation) ... ERROR
test_cluster_size_validation (starcluster.tests.test_cluster_validation.TestClusterValidation) ... ok
test_ebs_validation (starcluster.tests.test_cluster_validation.TestClusterValidation) ... ok
test_instance_type_validation (starcluster.tests.test_cluster_validation.TestClusterValidation) ... ok
test_keypair_validation (starcluster.tests.test_cluster_validation.TestClusterValidation) ... ok
test_permission_validation (starcluster.tests.test_cluster_validation.TestClusterValidation) ... ok
test_plugin_loading (starcluster.tests.test_cluster_validation.TestClusterValidation) ... ok
test_shell_validation (starcluster.tests.test_cluster_validation.TestClusterValidation) ... ok
test_bool_required (starcluster.tests.test_config.TestStarClusterConfig) ... ok
Test that config enforces a value to be one of a list of choices if ... ok
test_clusters (starcluster.tests.test_config.TestStarClusterConfig) ... ok
test_config_dne (starcluster.tests.test_config.TestStarClusterConfig) ... ok
Test that cyclical extends in the config raises an exception ... ok
Test that reading an empty config generates no errors and that aws ... ok
test_extends (starcluster.tests.test_config.TestStarClusterConfig) ... ok
test_get_cluster (starcluster.tests.test_config.TestStarClusterConfig) ... ok
test_int_required (starcluster.tests.test_config.TestStarClusterConfig) ... ok
Test that reading a non-INI formatted file raises an exception ... ok
test_keypair_not_defined (starcluster.tests.test_config.TestStarClusterConfig) ... ok
test_keypairs (starcluster.tests.test_config.TestStarClusterConfig) ... ok
test_missing_required (starcluster.tests.test_config.TestStarClusterConfig) ... ok
Test that config properly handles multiple instance types syntax ... ok
Loads all cluster sections in the test config in all possible orders ... ok
test_plugin_not_defined (starcluster.tests.test_config.TestStarClusterConfig) ... ok
test_plugins (starcluster.tests.test_config.TestStarClusterConfig) ... ok
test_valid_config_template (starcluster.tests.test_config.TestStarClusterConfig) ... ok
test_volume_not_defined (starcluster.tests.test_config.TestStarClusterConfig) ... ok
test_volumes (starcluster.tests.test_config.TestStarClusterConfig) ... ok
test_loaded_qhost_parser (starcluster.tests.test_sge_balancer.TestSGELoadBalancer) ... ok
test_loaded_qstat_parser (starcluster.tests.test_sge_balancer.TestSGELoadBalancer) ... ok
test_node_working (starcluster.tests.test_sge_balancer.TestSGELoadBalancer) ... ok
test_qacct_parser (starcluster.tests.test_sge_balancer.TestSGELoadBalancer) ... ok
test_qhost_parser (starcluster.tests.test_sge_balancer.TestSGELoadBalancer) ... ok
test_qstat_parser (starcluster.tests.test_sge_balancer.TestSGELoadBalancer) ... ok
test_args_and_kwargs (starcluster.tests.test_threadpool.TestThreadPool) ... ok
test_args_only (starcluster.tests.test_threadpool.TestThreadPool) ... ok
test_kwargs_only (starcluster.tests.test_threadpool.TestThreadPool) ... ok
test_no_args (starcluster.tests.test_threadpool.TestThreadPool) ... ok
test_threadpool_map (starcluster.tests.test_threadpool.TestThreadPool) ... ok
======================================================================
ERROR: test_aws_credentials_validation (starcluster.tests.test_cluster_validation.TestClusterValidation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/portage/dev-python/starcluster-0.93.3/work/StarCluster-0.93.3/starcluster/tests/test_cluster_validation.py", line 14, in test_aws_credentials_validation
    cluster._validate_credentials()
  File "/tmp/portage/dev-python/starcluster-0.93.3/work/StarCluster-0.93.3/starcluster/cluster.py", line 1867, in _validate_credentials
    if not self.ec2.is_valid_conn():
  File "/tmp/portage/dev-python/starcluster-0.93.3/work/StarCluster-0.93.3/starcluster/awsutils.py", line 481, in is_valid_conn
    self.get_all_instances()
  File "/tmp/portage/dev-python/starcluster-0.93.3/work/StarCluster-0.93.3/starcluster/awsutils.py", line 458, in get_all_instances
    filters=filters)
  File "/usr/lib64/python2.7/site-packages/boto/ec2/connection.py", line 467, in get_all_instances
    [('item', Reservation)], verb='POST')
  File "/usr/lib64/python2.7/site-packages/boto/connection.py", line 891, in get_list
    response = self.make_request(action, params, path, verb)
  File "/usr/lib64/python2.7/site-packages/boto/connection.py", line 877, in make_request
    return self._mexe(http_request)
  File "/usr/lib64/python2.7/site-packages/boto/connection.py", line 803, in _mexe
    raise e
error: [Errno 101] Network is unreachable
----------------------------------------------------------------------
Ran 39 tests in 54.197s
FAILED (errors=1)
 * ERROR: dev-python/starcluster-0.93.3 failed (test phase):
 *   Testing failed with CPython 2.7 in python_test_function() function
 * 
 * Call stack:
 *     ebuild.sh, line   85:  Called src_test
 *   environment, line 3988:  Called distutils_src_test '-v' 'starcluster/tests'
 *   environment, line 1336:  Called python_execute_nosetests '-P' '$(_distutils_get_PYTHONPATH)' '--' '-v' 'starcluster/tests'
 *   environment, line 2402:  Called python_execute_function 'python_test_function' '-v' 'starcluster/tests'
 *   environment, line 2337:  Called die
 * The specific snippet of code:
 *                       die "${failure_message}";
 * 
 * If you need support, post the output of `emerge --info '=dev-python/starcluster-0.93.3'`,
 * the complete build log and the output of `emerge -pqv '=dev-python/starcluster-0.93.3'`.
 * The complete build log is located at '/var/log/portage/dev-python:starcluster-0.93.3:20120714-005236.log'.
 * For convenience, a symlink to the build log is located at '/tmp/portage/dev-python/starcluster-0.93.3/temp/build.log'.
 * The ebuild environment file is located at '/tmp/portage/dev-python/starcluster-0.93.3/temp/environment'.
 * Working directory: '/tmp/portage/dev-python/starcluster-0.93.3/work/StarCluster-0.93.3'
 * S: '/tmp/portage/dev-python/starcluster-0.93.3/work/StarCluster-0.93.3'
```
