### ISSUE TITLE
bug with listvolumes

### ISSUE THREAD

**Issue by jtriley** [jtriley/StarCluster#16]
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/StarCluster-0.9999-py2.6.egg/starcluster/cli.py", line 160, in main
    sc.execute(args)
  File "/usr/local/lib/python2.6/dist-packages/StarCluster-0.9999-py2.6.egg/starcluster/commands/listvolumes.py", line 41, in execute
    self.ec2.list_volumes(**self.options_dict)
  File "/usr/local/lib/python2.6/dist-packages/StarCluster-0.9999-py2.6.egg/starcluster/awsutils.py", line 1012, in list_volumes
    vols.sort(key=lambda x: x.create_time)
AttributeError: 'NoneType' object has no attribute 'sort'

**Comment by jtriley** [comment]
should be fixed by better AWS exception handling via f46f8d4d68b05b630776
