### ISSUE TITLE
Error at start starcluster ebsimage

### ISSUE THREAD

**Issue by Infectedman** [jtriley/StarCluster#174]
We can not create an new AMI
[ec2-user@ip-10-244-167-166 ~]$ starcluster ebsimage i-1bc67164 starcluster
StarCluster - (http://web.mit.edu/starcluster) (v. 0.93.3)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

> > > Removing private data...
> > > !!! ERROR - Error occurred while creating image
> > > !!! ERROR - Remote SSH access for user 'root' denied via authorized_keys
> > > !!! ERROR -
> > > !!! ERROR - This usually means the AMI you're using has been configured
> > > !!! ERROR - to deny SSH access for the 'root' user. Either fix your AMI
> > > !!! ERROR - or use one of the StarCluster supported AMIs. You can obtain
> > > !!! ERROR - a list of StarCluster supported AMIs using the 'listpublic'
> > > !!! ERROR - command:
> > > !!! ERROR -
> > > !!! ERROR -     $ starcluster listpublic
> > > !!! ERROR -
> > > !!! ERROR - If you need to customize one of the StarCluster supported
> > > !!! ERROR - AMIs simply launch an instance of the AMI, login remotely,
> > > !!! ERROR - configure the instance, and then use the 'ebsimage' command
> > > !!! ERROR - to create a new EBS AMI from the instance with your changes:
> > > !!! ERROR -
> > > !!! ERROR -     $ starcluster ebsimage <instance-id> <image-name>
> > > !!! ERROR -
> > > !!! ERROR - Pass the --help flag to the 'ebsimage' command for more
> > > !!! ERROR - details.

Writes in the log ~/.startcluster/logs/debug.log

2012-11-17 10:48:29,399 PID: 2187 config.py:551 - DEBUG - Loading config
2012-11-17 10:48:29,399 PID: 2187 config.py:118 - DEBUG - Loading file: /home/ec2-user/.starcluster/config
2012-11-17 10:48:29,402 PID: 2187 awsutils.py:54 - DEBUG - creating self._conn w/ connection_authenticator kwargs = {'proxy_user': None, 'proxy_pass': None, 'proxy_port': None, 'proxy': None, 'is_secure': True, 'path': '/', 'region': RegionInfo:us-east-1, 'port': None}
2012-11-17 10:48:29,563 PID: 2187 __init__.py:75 - DEBUG - loading private key /home/ec2-user/.ssh/cuda.rsa
2012-11-17 10:48:29,564 PID: 2187 **init**.py:167 - DEBUG - Using private key /home/ec2-user/.ssh/cuda.rsa (rsa)
2012-11-17 10:48:29,565 PID: 2187 image.py:40 - INFO - Removing private data...
2012-11-17 10:48:29,565 PID: 2187 **init**.py:97 - DEBUG - connecting to host ec2-184-73-103-3.compute-1.amazonaws.com on port 22 as user root
2012-11-17 10:48:30,538 PID: 2187 **init**.py:186 - DEBUG - creating sftp connection
2012-11-17 10:48:30,906 PID: 2187 **init**.py:124 - DEBUG - Garbage packet received
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/StarCluster-0.93.3-py2.6.egg/starcluster/sshutils/**init**.py", line 121, in connect
    assert self.sftp is not None
  File "/usr/lib/python2.6/site-packages/StarCluster-0.93.3-py2.6.egg/starcluster/sshutils/**init**.py", line 187, in sftp
    self._sftp = ssh.SFTPClient.from_transport(self.transport)
  File "/usr/lib/python2.6/site-packages/ssh-1.7.13-py2.6.egg/ssh/sftp_client.py", line 106, in from_transport
    return cls(chan)
  File "/usr/lib/python2.6/site-packages/ssh-1.7.13-py2.6.egg/ssh/sftp_client.py", line 87, in __init__
    server_version = self._send_version()
  File "/usr/lib/python2.6/site-packages/ssh-1.7.13-py2.6.egg/ssh/sftp.py", line 108, in _send_version
    t, data = self._read_packet()
  File "/usr/lib/python2.6/site-packages/ssh-1.7.13-py2.6.egg/ssh/sftp.py", line 179, in _read_packet
    raise SFTPError('Garbage packet received')
SFTPError: Garbage packet received
2012-11-17 10:48:30,907 PID: 2187 image.py:213 - ERROR - Error occurred while creating image
2012-11-17 10:48:30,907 PID: 2187 cli.py:279 - ERROR - Remote SSH access for user 'root' denied via authorized_keys
...

Please, give advice

**Comment by jtriley** [comment]
My apologies for losing track of this. The issue is that StarCluster cannot login as root most likely due to your AMI being configured to disallow root login over SSH by default. Depending on which AMI you were using the fix may vary.

Most Ubuntu/Redhat based AMIs by now use cloudinit. IIRC by default cloudinit modifies root's authorized_keys to disable SSH login for root. If in fact your base AMI was using cloudinit (which it most likely was) then the upcoming 0.94 version of StarCluster should fix this issue by enabling root login via the master's userdata (assuming you launch the image host with StarCluster).
