### ISSUE TITLE
error running stacluster command:  starcluster listclusters

### ISSUE THREAD

**Issue by stratosef** [jtriley/StarCluster#180]
I have just downloaded and used the development version.
Many things work well, but I got the following error:

[root@nas-3-0 StarCluster-develop]# starcluster listclusters
StarCluster - (http://star.mit.edu/cluster) (v. 0.9999)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

---
## smallcluster (security group: @sc-smallcluster)

!!! ERROR - Unhandled exception occured
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/StarCluster-0.9999-py2.6.egg/starcluster/cli.py", line 257, in main
    sc.execute(args)
  File "/usr/lib/python2.6/site-packages/StarCluster-0.9999-py2.6.egg/starcluster/commands/listclusters.py", line 19, in execute
    show_ssh_status=self.opts.show_ssh_status)
  File "/usr/lib/python2.6/site-packages/StarCluster-0.9999-py2.6.egg/starcluster/cluster.py", line 252, in list_clusters
    nodes = cl.nodes
  File "/usr/lib/python2.6/site-packages/StarCluster-0.9999-py2.6.egg/starcluster/cluster.py", line 651, in nodes
    if n.is_master():
  File "/usr/lib/python2.6/site-packages/StarCluster-0.9999-py2.6.egg/starcluster/node.py", line 819, in is_master
    return self.alias == "master"
  File "/usr/lib/python2.6/site-packages/StarCluster-0.9999-py2.6.egg/starcluster/node.py", line 114, in alias
    aliases = aliasestxt.splitlines()[2:]
AttributeError: 'NoneType' object has no attribute 'splitlines'

!!! ERROR - Oops! Looks like you've found a bug in StarCluster
!!! ERROR - Crash report written to: /root/.starcluster/logs/crash-report-4008.txt
!!! ERROR - Please remove any sensitive data from the crash report
!!! ERROR - and submit it to starcluster@mit.edu

**Comment by jtriley** [comment]
This should be fixed in the latest code. Please reopen if the problem still persists.
