### ISSUE TITLE
clustersetup.setup_cluster_user tries to delete/replace root user

### ISSUE THREAD

**Issue by FinchPowers** [jtriley/StarCluster#217]
Root cannot be deleted and the call fails. I'm not sure if this is because I'm using an AMI that is not properly configured. If so, just close this ticket.

Here is the (slightly extended) stack trace I get when starting the cluster.

```
>>> Running plugin starcluster.clustersetup.DefaultClusterSetup
>>> Configuring hostnames...
1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
>>> Creating cluster user: sgeadmin (uid: 0, gid: 0)
1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
!!! ERROR - -------threadpool exc start---------
!!! ERROR - tb_msg:
!!! ERROR - Traceback (most recent call last):
File "/home/fmlheureux/workspace/StarCluster/starcluster/threadpool.py", line 31, in run
job.run()
File "/home/fmlheureux/workspace/StarCluster/starcluster/threadpool.py", line 58, in run
r = self.method(*self.args, **self.kwargs)
File "/home/fmlheureux/workspace/StarCluster/starcluster/clustersetup.py", line 186, in _add_user_to_node
node.remove_user(username)
File "/home/fmlheureux/workspace/StarCluster/starcluster/node.py", line 621, in remove_user
self.ssh.execute('userdel %s' % name)
File "/home/fmlheureux/workspace/StarCluster/starcluster/sshutils/__init__.py", line 541, in execute
msg, command, exit_status, out_str)
RemoteCommandFailed: remote command 'source /etc/profile && userdel root' failed with status 8:
userdel: user root is currently logged in

!!! ERROR - e:
!!! ERROR - remote command 'source /etc/profile && userdel root' failed with status 8:
userdel: user root is currently logged in
!!! ERROR - jid:
!!! ERROR - master
!!! ERROR - -------threadpool exc end-----------
!!! ERROR - Error occured while running plugin 'starcluster.clustersetup.DefaultClusterSetup':
!!! ERROR - error occurred in job (id=master): remote command 'source /etc/profile &&      userdel root' failed with status 8:
userdel: user root is currently logged in
Traceback (most recent call last):
File "/home/fmlheureux/workspace/StarCluster/starcluster/threadpool.py", line 31, in run
job.run()
File "/home/fmlheureux/workspace/StarCluster/starcluster/threadpool.py", line 58, in run
r = self.method(*self.args, **self.kwargs)
File "/home/fmlheureux/workspace/StarCluster/starcluster/clustersetup.py", line 186, in _add_user_to_node
node.remove_user(username)
File "/home/fmlheureux/workspace/StarCluster/starcluster/node.py", line 621, in remove_user
self.ssh.execute('userdel %s' % name)
File "/home/fmlheureux/workspace/StarCluster/starcluster/sshutils/__init__.py", line 541, in execute
msg, command, exit_status, out_str)
RemoteCommandFailed: remote command 'source /etc/profile && userdel root' failed with status 8:
userdel: user root is currently logged in
```

**Comment by jtriley** [comment]
Woah that's weird, thanks for reporting. Looking into this today.

**Comment by jtriley** [comment]
We figured out the issue on IRC ( **#starcluster** ) but detailing the issue here as well for for others that may come across this issue:

When configuring the `cluster_user` StarCluster first checks to see if the user's $HOME folder exists and if so creates the `cluster_user` with the same UID/GID of the existing $HOME folder. If this wasn't the case StarCluster would have to chown potentially thousands of files (a very time consuming operation) in the `cluster_user`'s home folder in order to get the permissions right in the case that the newly created UID/GID doesn't match the original UID/GID of the $HOME folder when it was created.

With that said, the issue here is that @FinchPowers' custom AMI mistakenly baked in a /home/sgeadmin folder that was owned by root (UID/GID=0). The fix here is to simply rebuild the AMI without /home/sgeadmin or at the very least without /home/sgeadmin being owned as root.

@FinchPowers is now working on a PR that will raise an error when this event happens so that users are properly warned about their misconfigured AMI.

**Comment by FinchPowers** [comment]
See PR #227
