### ISSUE TITLE
ERROR - Oops! Looks like you've found a bug in StarCluster

### ISSUE THREAD

**Issue by rezuma** [jtriley/StarCluster#223]
# The following lines are desirable for IPv6 capable hosts

::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
# Added by cloud-init

127.0.1.1   domU-12-31-39-09-CD-4F.compute-1.internal domU-12-31-39-09-CD-4F

2013-02-13 17:04:02,146 PID: 14394 node.py:606 - INFO - Starting NFS server on master
2013-02-13 17:04:02,168 PID: 14394 **init**.py:543 - DEBUG - Rather than invoking init scripts through /etc/init.d, use the service(8)
2013-02-13 17:04:02,168 PID: 14394 **init**.py:543 - DEBUG - utility, e.g. service portmap start
2013-02-13 17:04:02,169 PID: 14394 **init**.py:543 - DEBUG - 
2013-02-13 17:04:02,169 PID: 14394 **init**.py:543 - DEBUG - Since the script you are attempting to invoke has been converted to an
2013-02-13 17:04:02,169 PID: 14394 **init**.py:543 - DEBUG - Upstart job, you may also use the start(8) utility, e.g. start portmap
2013-02-13 17:04:02,245 PID: 14394 **init**.py:540 - DEBUG - command 'mount -t rpc_pipefs sunrpc /var/lib/nfs/rpc_pipefs/' failed with status 32
2013-02-13 17:04:02,245 PID: 14394 **init**.py:543 - DEBUG - mount: unknown filesystem type 'rpc_pipefs'
2013-02-13 17:04:02,430 PID: 14394 **init**.py:543 - DEBUG - \* Exporting directories for NFS kernel daemon...
2013-02-13 17:04:02,431 PID: 14394 **init**.py:543 - DEBUG - ...done.
2013-02-13 17:04:02,431 PID: 14394 **init**.py:543 - DEBUG - \* Starting NFS kernel daemon
2013-02-13 17:04:02,431 PID: 14394 **init**.py:543 - DEBUG - ...done.
2013-02-13 17:04:02,431 PID: 14394 **init**.py:543 - DEBUG - exportfs: scandir /etc/exports.d: No such file or directory
2013-02-13 17:04:02,431 PID: 14394 **init**.py:543 - DEBUG - 
2013-02-13 17:04:02,505 PID: 14394 **init**.py:543 - DEBUG - exportfs: scandir /etc/exports.d: No such file or directory
2013-02-13 17:04:02,505 PID: 14394 **init**.py:543 - DEBUG - 
2013-02-13 17:04:02,505 PID: 14394 utils.py:93 - INFO - Setting up NFS took 0.006 mins
2013-02-13 17:04:02,506 PID: 14394 clustersetup.py:221 - INFO - Configuring passwordless ssh for root
2013-02-13 17:04:02,552 PID: 14394 threadpool.py:123 - INFO - Shutting down threads...
2013-02-13 17:04:02,553 PID: 14394 threadpool.py:135 - DEBUG - unfinished_tasks = 20
2013-02-13 17:04:03,670 PID: 14394 cli.py:287 - DEBUG - Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/StarCluster-0.93.3-py2.6.egg/starcluster/cli.py", line 255, in main
    sc.execute(args)
  File "/usr/lib/python2.6/site-packages/StarCluster-0.93.3-py2.6.egg/starcluster/commands/start.py", line 194, in execute
    validate_running=validate_running)
  File "/usr/lib/python2.6/site-packages/StarCluster-0.93.3-py2.6.egg/starcluster/cluster.py", line 1414, in start
    return self._start(create=create, create_only=create_only)
  File "<string>", line 2, in _start
  File "/usr/lib/python2.6/site-packages/StarCluster-0.93.3-py2.6.egg/starcluster/utils.py", line 87, in wrap_f
    res = func(_arg, *_kargs)
  File "/usr/lib/python2.6/site-packages/StarCluster-0.93.3-py2.6.egg/starcluster/cluster.py", line 1437, in _start
    self.setup_cluster()
  File "/usr/lib/python2.6/site-packages/StarCluster-0.93.3-py2.6.egg/starcluster/cluster.py", line 1446, in setup_cluster
    self._setup_cluster()
  File "<string>", line 2, in _setup_cluster
  File "/usr/lib/python2.6/site-packages/StarCluster-0.93.3-py2.6.egg/starcluster/utils.py", line 87, in wrap_f
    res = func(_arg, *_kargs)
  File "/usr/lib/python2.6/site-packages/StarCluster-0.93.3-py2.6.egg/starcluster/cluster.py", line 1460, in _setup_cluster
    self.cluster_shell, self.volumes)
  File "/usr/lib/python2.6/site-packages/StarCluster-0.93.3-py2.6.egg/starcluster/clustersetup.py", line 350, in run
    self._setup_passwordless_ssh()
  File "/usr/lib/python2.6/site-packages/StarCluster-0.93.3-py2.6.egg/starcluster/clustersetup.py", line 225, in _setup_passwordless_ssh
    auth_conn_key=True)
  File "/usr/lib/python2.6/site-packages/StarCluster-0.93.3-py2.6.egg/starcluster/node.py", line 420, in generate_key_for_user
    key = self.ssh.generate_rsa_key()
  File "/usr/lib/python2.6/site-packages/StarCluster-0.93.3-py2.6.egg/starcluster/sshutils/__init__.py", line 200, in generate_rsa_key
    return ssh.RSAKey.generate(2048)
  File "/usr/lib/python2.6/site-packages/ssh-1.7.13-py2.6.egg/ssh/rsakey.py", line 140, in generate
    rsa = RSA.generate(bits, rng.read, progress_func)
  File "/usr/lib64/python2.6/site-packages/Crypto/PublicKey/RSA.py", line 508, in generate
    obj = _RSA.generate_py(bits, rf, progress_func, e)    # TODO: Don't use legacy _RSA module
  File "/usr/lib64/python2.6/site-packages/Crypto/PublicKey/_RSA.py", line 50, in generate_py
    p = pubkey.getStrongPrime(bits>>1, obj.e, 1e-12, randfunc)
  File "/usr/lib64/python2.6/site-packages/Crypto/Util/number.py", line 264, in getStrongPrime
    return _fastmath.getStrongPrime(long(N), long(e), false_positive_prob,
AttributeError: 'module' object has no attribute 'getStrongPrime'

---------- SYSTEM INFO ----------
StarCluster: 0.93.3
Python: 2.6.6 (r266:84292, Sep 11 2012, 08:34:23)  [GCC 4.4.6 20120305 (Red Hat 4.4.6-4)]
Platform: Linux-2.6.32-279.14.1.el6.x86_64-x86_64-with-centos-6.3-Final
boto: 2.3.0
ssh: 1.7.13
Crypto: 2.6
jinja2: 2.6
decorator: 3.3.1

**Comment by jtriley** [comment]
This looks like an issue with PyCrypto but not sure what the solution is at the moment. Have you tried recompiling/reinstalling PyCrypto? /cc @dlitz

**Comment by rezuma** [comment]
i will try, thanks.
I didnt have this error on the first machine I installed Starcluster on, so it could be PyCrypto installation.

**Comment by dlitz** [comment]
That's really strange, and definitely some kind of installation issue.  Maybe you're running an older version of _fastmath.so with a newer version of PyCrypto's .py files?

**Comment by jtriley** [comment]
@dlitz Thanks a bunch for jumping in - I just wanted to make sure this wasn't something you had seen before. My googling didn't seem to turn up anything but you never know. Definitely an issue with the compiled _fastmath.so. For me if I run `nm _fastmath.so` I see the getStrongPrime method:

```
% nm Crypto/PublicKey/_fastmath.so | grep -i getstrongprime
0000000000006b30 t getStrongPrime
```

Perhaps the compilation step for `_fastmath.so` doesn't cause the entire installation process to fail for some reason if there's an error? Maybe an issue with an older/newer version of libgmp/mpir?

@rezuma Was PyCrypto installed using yum on CentOS-6.3 or did you custom compile Python/PyCrypto? Can you test manually compiling and installing PyCrypto 2.6?

**Comment by rezuma** [comment]
ok.

I think i found the problem, I installed the PyCrypto with yum first.
Then i realized that yum (at least in CentOS) installs the version 2.0.1-22 which is not enough for Starcluster.
Then i downloaded and installed PyCrypto 2.6 with python setup.py.
So at that point they were both installed !!??
Anyway, i uninstalled with yum the 2.0.1 and resintalled 2.6 and now i dont see that error anymore !! :)

But, i am seeing this other one
/usr/lib64/python2.6/site-packages/Crypto/Util/number.py:57: PowmInsecureWarning: Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.
  _warn("Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.", PowmInsecureWarning)

Thanks a lot!!!

Rezuma

**Comment by jtriley** [comment]
@rezuma Awesome, glad you got things working. In order to get rid of the warning about libgmp you'll either need to install libgmp or if it's already installed you'll need to upgrade libgmp >= version 5 and then rebuild and reinstall PyCrypto. I'm going to close this issue now. Thanks for following up!

**Comment by twiecki** [comment]
I also had this problem. In my case pycrypto was a recent version but it was not built with support fastmath because I didn't have libgmp installed.

Perhaps a try/except with a useful error message could help here?

**Comment by twiecki** [comment]
Hm, actually that did not fix the problem. Not sure what else could be the problem could be.
