### ISSUE TITLE
Loadbalancer timeout on unexisting node

### ISSUE THREAD

**Issue by FinchPowers** [jtriley/StarCluster#226]
It seems that sometimes nodes remain cached somehow. I have an issue where a timeout is caused by unexisting node. Here is part of the content from my debug.log
- It adds node001. 
- Existing node returns the list properly with master and node001.
- Thread pool returns an exception on ... node003.

2013-02-28 08:11:18,374 PID: 625 threadpool.py:135 - DEBUG - unfinished_tasks = 1
2013-02-28 08:11:19,375 PID: 625 threadpool.py:135 - DEBUG - unfinished_tasks = 1
2013-02-28 08:11:19,480 PID: 625 **init**.py:91 - DEBUG - connecting to host ec2-184-73-143-251.compute-1.amazonaws.com on port 22 as user root
2013-02-28 08:11:19,840 PID: 625 **init**.py:180 - DEBUG - creating sftp connection
2013-02-28 08:11:20,377 PID: 625 utils.py:98 - INFO - Waiting for cluster to come up took 3.048 mins
2013-02-28 08:11:20,377 PID: 625 cluster.py:991 - DEBUG - Adding node(s): ['node001']
2013-02-28 08:11:20,483 PID: 625 cluster.py:751 - DEBUG - existing nodes: {u'i-83bc64f2': <Node: master (i-83bc64f2)>, u'i-f0cba783': <Node: node001 (i-f0cba783)>}
2013-02-28 08:11:20,483 PID: 625 cluster.py:754 - DEBUG - updating existing node i-83bc64f2 in self._nodes
2013-02-28 08:11:20,483 PID: 625 cluster.py:754 - DEBUG - updating existing node i-f0cba783 in self._nodes
2013-02-28 08:11:20,483 PID: 625 cluster.py:767 - DEBUG - returning self._nodes = [<Node: master (i-83bc64f2)>, <Node: node001 (i-f0cba783)>]
2013-02-28 08:11:20,584 PID: 625 cluster.py:751 - DEBUG - existing nodes: {u'i-83bc64f2': <Node: master (i-83bc64f2)>, u'i-f0cba783': <Node: node001 (i-f0cba783)>}
2013-02-28 08:11:20,584 PID: 625 cluster.py:754 - DEBUG - updating existing node i-83bc64f2 in self._nodes
2013-02-28 08:11:20,585 PID: 625 cluster.py:754 - DEBUG - updating existing node i-f0cba783 in self._nodes
2013-02-28 08:11:20,585 PID: 625 cluster.py:767 - DEBUG - returning self._nodes = [<Node: master (i-83bc64f2)>, <Node: node001 (i-f0cba783)>]
2013-02-28 08:11:20,585 PID: 625 cluster.py:1672 - INFO - Running plugin starcluster.clustersetup.DefaultClusterSetup
2013-02-28 08:11:20,585 PID: 625 clustersetup.py:104 - INFO - Configuring hostnames...
2013-02-28 08:11:20,585 PID: 625 clustersetup.py:105 - DEBUG - It's 2013-02-28 13:11:20.585754
2013-02-28 08:11:20,586 PID: 625 threadpool.py:135 - DEBUG - unfinished_tasks = 1
2013-02-28 08:11:20,714 PID: 625 __init__.py:524 - DEBUG - executing remote command: source /etc/profile && hostname -F /etc/hostname
2013-02-28 08:11:20,769 PID: 625 **init**.py:548 - DEBUG - output of 'source /etc/profile && hostname -F /etc/hostname':

2013-02-28 08:11:21,587 PID: 625 threadpool.py:154 - ERROR - -------threadpool exc start---------
2013-02-28 08:11:21,587 PID: 625 threadpool.py:158 - ERROR - tb_msg:
2013-02-28 08:11:21,587 PID: 625 threadpool.py:159 - ERROR - Traceback (most recent call last):
  File "/home/fmlheureux/workspace/StarCluster/starcluster/threadpool.py", line 31, in run
    job.run()
  File "/home/fmlheureux/workspace/StarCluster/starcluster/threadpool.py", line 58, in run
    r = self.method(_self.args, *_self.kwargs)
  File "/home/fmlheureux/workspace/StarCluster/starcluster/node.py", line 787, in add_to_etc_hosts
    self.remove_from_etc_hosts(nodes)
  File "/home/fmlheureux/workspace/StarCluster/starcluster/node.py", line 800, in remove_from_etc_hosts
    self.ssh.remove_lines_from_file('/etc/hosts', '|'.join(aliases))
  File "/home/fmlheureux/workspace/StarCluster/starcluster/sshutils/**init**.py", line 278, in remove_lines_from_file
    lines = self.get_remote_file_lines(remote_file, regex, matching=False)
  File "/home/fmlheureux/workspace/StarCluster/starcluster/sshutils/**init**.py", line 256, in get_remote_file_lines
    f = self.remote_file(remote_file, 'r') 
  File "/home/fmlheureux/workspace/StarCluster/starcluster/sshutils/**init**.py", line 292, in remote_file
    rfile = self.sftp.open(file, mode)
  File "/home/fmlheureux/datacratic_starcluster/local/lib/python2.7/site-packages/paramiko-1.9.0-py2.7.egg/paramiko/sftp_client.py", line 245, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
  File "/home/fmlheureux/datacratic_starcluster/local/lib/python2.7/site-packages/paramiko-1.9.0-py2.7.egg/paramiko/sftp_client.py", line 635, in _request
    return self._read_response(num)
  File "/home/fmlheureux/datacratic_starcluster/local/lib/python2.7/site-packages/paramiko-1.9.0-py2.7.egg/paramiko/sftp_client.py", line 665, in _read_response
    t, data = self._read_packet()
  File "/home/fmlheureux/datacratic_starcluster/local/lib/python2.7/site-packages/paramiko-1.9.0-py2.7.egg/paramiko/sftp.py", line 175, in _read_packet
    x = self._read_all(4)
  File "/home/fmlheureux/datacratic_starcluster/local/lib/python2.7/site-packages/paramiko-1.9.0-py2.7.egg/paramiko/sftp.py", line 159, in _read_all    x = self.sock.recv(n)
  File "/home/fmlheureux/datacratic_starcluster/local/lib/python2.7/site-packages/paramiko-1.9.0-py2.7.egg/paramiko/channel.py", line 611, in recv
    raise socket.timeout()timeout

2013-02-28 08:11:21,587 PID: 625 threadpool.py:160 - ERROR - e:
2013-02-28 08:11:21,588 PID: 625 threadpool.py:161 - ERROR -
2013-02-28 08:11:21,588 PID: 625 threadpool.py:162 - ERROR - jid: 
2013-02-28 08:11:21,588 PID: 625 threadpool.py:163 - ERROR - node003
2013-02-28 08:11:21,588 PID: 625 threadpool.py:164 - ERROR - -------threadpool exc end-----------
2013-02-28 08:11:21,588 PID: 625 cluster.py:1682 - ERROR - Error occured while running plugin 'starcluster.clustersetup.DefaultClusterSetup':
2013-02-28 08:11:21,589 PID: 625 cluster.py:1748 - ERROR - Traceback (most recent call last):
  File "/home/fmlheureux/workspace/StarCluster/starcluster/cluster.py", line 1744, in recover
    no_create=True)
  File "/home/fmlheureux/workspace/StarCluster/starcluster/cluster.py", line 994, in add_nodes
    self.run_plugins(method_name="on_add_node", node=node)
  File "/home/fmlheureux/workspace/StarCluster/starcluster/cluster.py", line 1648, in run_plugins
    self.run_plugin(plug, method_name=method_name, node=node)
  File "/home/fmlheureux/workspace/StarCluster/starcluster/cluster.py", line 1673, in run_plugin
    func(*args)
  File "/home/fmlheureux/workspace/StarCluster/starcluster/clustersetup.py", line 413, in on_add_node
    self._setup_hostnames(nodes=[node])
  File "/home/fmlheureux/workspace/StarCluster/starcluster/clustersetup.py", line 108, in _setup_hostnames
    self.pool.wait(numtasks=len(nodes))
  File "/home/fmlheureux/workspace/StarCluster/starcluster/threadpool.py", line 143, in wait
    "An error occurred in ThreadPool", self._exception_queue.queue)
ThreadPoolException: An error occurred in ThreadPool

**Comment by FinchPowers** [comment]
This is likely due to the issue where thread pool exception queue was not cleared.
