### ISSUE TITLE
sshmaster under windows won't work

### ISSUE THREAD

**Issue by sebastien-bratieres** [jtriley/StarCluster#254]
Windows 8 Enterprise. Using cmd.exe from Windows as the command shell.

Workaround: Putty.

C:\Users\bratieress>starcluster start -c testcluster mytestcluster
StarCluster - (http://web.mit.edu/starcluster) (v. 0.93.3)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

> > > Validating cluster template settings...
> > > Cluster template settings are valid
> > > Starting cluster...
> > > Launching a 2-node cluster...
> > > Creating security group @sc-mytestcluster...
> > > Reservation:r-65ef9c0e
> > > Waiting for cluster to come up... (updating every 30s)
> > > Waiting for all nodes to be in a 'running' state...
> > > 2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Waiting for SSH to come up on all nodes...
> > > 2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Waiting for cluster to come up took 1.681 mins
> > > The master node is ec2-184-73-83-95.compute-1.amazonaws.com
> > > Setting up the cluster...
> > > Attaching volume vol-b70902ef to master node on /dev/sdz ...
> > > Configuring hostnames...
> > > 2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > !!! ERROR - volume has more than one partition, please specify which partition t
> > > o use (e.g. partition=0, partition=1, etc.) in the volume's config
> > > Creating cluster user: None (uid: 1001, gid: 1001)
> > > 2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Configuring scratch space for user(s): sgeadmin
> > > 2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Configuring /etc/hosts on each node
> > > 2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Starting NFS server on master
> > > Configuring NFS exports path(s):
> > > /home /shared
> > > Mounting all NFS export path(s) on 1 worker node(s)
> > > !!! ERROR - command 'mount /shared' failed with status 32              |   0%
> > > 1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Setting up NFS took 0.143 mins
> > > Configuring passwordless ssh for root
> > > Configuring passwordless ssh for sgeadmin
> > > Shutting down threads...
> > > 20/20 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Configuring SGE...
> > > Configuring NFS exports path(s):
> > > /opt/sge6
> > > Mounting all NFS export path(s) on 1 worker node(s)
> > > 1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Setting up NFS took 0.069 mins
> > > Installing Sun Grid Engine...
> > > 1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Creating SGE parallel environment 'orte'
> > > 2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Adding parallel environment 'orte' to queue 'all.q'
> > > Shutting down threads...
> > > 20/20 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Running plugin pkginstaller
> > > Installing the following packages on all nodes:
> > > libxt6, libxmu6, libxtst6, libxpm4
> > > 2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Configuring cluster took 1.874 mins
> > > Starting cluster took 3.594 mins

============ ssh to master node ===============

C:\Users\bratieress>starcluster sshmaster mytestcluster
StarCluster - (http://web.mit.edu/starcluster) (v. 0.93.3)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

> > > Starting Pure-Python SSH shell...
> > > Line-buffered terminal emulation. Press F6 or ^Z to send EOF.

eval $(resize)
root@master:~# eval $(resize)
←7←[r←[999;999H←[6nls
resize: unknown character, exiting.
root@master:~# s
s: command not found
root@master:~# ls
ls
root@master:~# ls -al
ls -al
total 28
drwx------  4 root root 4096 May 23 16:30 ←[0m←[01;34m.←[0m
drwxr-xr-x 25 root root 4096 May 23 16:30 ←[01;34m..←[0m
-rw-r--r--  1 root root   17 Jan  9 07:18 .bash_aliases
-rw-r--r--  1 root root 3106 Apr 19  2012 .bashrc
drwx------  2 root root 4096 May 23 16:30 ←[01;34m.cache←[0m
-rw-r--r--  1 root root  140 Apr 19  2012 .profile
drwx------  2 root root 4096 May 23 16:31 ←[01;34m.ssh←[0m
root@master:~# exit
exit
logout

**\* EOF ***

exit
Traceback (most recent call last):
  File "C:\Python27\Scripts\starcluster-script.py", line 8, in <module>
    load_entry_point('starcluster==0.93.3', 'console_scripts', 'starcluster')()
  File "C:\Python27\lib\site-packages\starcluster-0.93.3-py2.7.egg\starcluster\c
li.py", line 312, in main
    StarClusterCLI().main()
  File "C:\Python27\lib\site-packages\starcluster-0.93.3-py2.7.egg\starcluster\c
li.py", line 255, in main
    sc.execute(args)
  File "C:\Python27\lib\site-packages\starcluster-0.93.3-py2.7.egg\starcluster\c
ommands\sshmaster.py", line 36, in execute
^C
C:\Users\bratieress>    forward_x11=self.opts.forward_x11)
  File "C:\Python27\lib\site-packages\starcluster-0.93.3-py2.7.egg\starcluster\c
luster.py", line 115, in ssh_to_master
    forward_x11=forward_x11)
  File "C:\Python27\lib\site-packages\starcluster-0.93.3-py2.7.egg\starcluster\c
luster.py", line 1918, in ssh_to_master
    forward_x11=forward_x11)
  File "C:\Python27\lib\site-packages\starcluster-0.93.3-py2.7.egg\starcluster\c
luster.py", line 1926, in ssh_to_node
    return node.shell(user=user, forward_x11=forward_x11, command=command)
  File "C:\Python27\lib\site-packages\starcluster-0.93.3-py2.7.egg\starcluster\n
ode.py", line 931, in shell
    self.ssh.interactive_shell(user=user)
  File "C:\Python27\lib\site-packages\starcluster-0.93.3-py2.7.egg\starcluster\s
shutils__init__.py", line 626, in interactive_shell
    self.switch_user(orig_user)
  File "C:\Python27\lib\site-packages\starcluster-0.93.3-py2.7.egg\starcluster\s
shutils__init__.py", line 609, in switch_user
    log.debug("already connected as user %s" % user)
  File "C:\Python27\lib\logging__init__.py", line 1137, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "C:\Python27\lib\logging__init__.py", line 1268, in _log
    self.handle(record)
  File "C:\Python27\lib\logging__init__.py", line 1278, in handle
    self.callHandlers(record)
  File "C:\Python27\lib\logging__init__.py", line 1318, in callHandlers
    hdlr.handle(record)
  File "C:\Python27\lib\logging__init__.py", line 749, in handle
    self.emit(record)
  File "C:\Python27\lib\logging\handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "C:\Python27\lib\logging\handlers.py", line 155, in shouldRollover
    self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
KeyboardInterrupt

**Comment by rsignell-usgs** [comment]
So is putty really the only way to solve this problem when using Windows?
I thought I might be able to avoid this problem by using powershell, but I was wrong:

![12-3-2014 6-12-20 pm](https://cloud.githubusercontent.com/assets/1872600/5290763/fdc61b3e-7b17-11e4-8cf4-63feedb180d1.png)

**Comment by procaddie** [comment]
Now I have the almost same problem. How did you solve it?

**Comment by rsignell-usgs** [comment]
I never solved it.   Just gave up.  :cry:

**Comment by procaddie** [comment]
Only three of us faced this problem? I google it. But what I found about it was only this page. How do windows-users use the Starcluster???

**Comment by hitblz** [comment]
Recently I encountered the same problem, too. 
![error1](https://cloud.githubusercontent.com/assets/24424921/20955347/7e5b2b56-bc7d-11e6-87b5-3883ac916234.PNG)

Have you solved this problem now? @sebastien-bratieres, @rsignell-usgs , @procaddie .
