### ISSUE TITLE
Problem to create customize EBS IMAGE (AMI) using starcluster 

### ISSUE THREAD

**Issue by aaravindanarun** [jtriley/StarCluster#258]
Problem to create own customize EBS (AMI) using Starcluster. Installed required tools  on CentOS 6.3 - 64 Bit Version.
1. starcluster start -o -s 1 -i t1.micro -n ami-6f92dc3d imagehost

> > > Using default cluster template: smallcluster
> > > Validating cluster template settings...
> > > Cluster template settings are valid
> > > Starting cluster...
> > > Launching a 1-node cluster...
> > > Creating security group @sc-imagehost...
> > > Opening tcp port range 80-80 for CIDR 0.0.0.0/0
> > > Reservation:r-cb1f399c
> > > Starting cluster took 0.031 mins
## imagehost (security group: @sc-imagehost)

Launch time: 2013-06-11 10:26:54
Uptime: 0 days, 00:05:16
Zone: ap-southeast-1a
Keypair: starcluster
EBS volumes:
    vol-d618f5de on master:/dev/sda (status: attached)
Cluster nodes:
     master running i-d9eb1c8f ec2-175-41-168-194.ap-southeast-1.compute.amazonaws.com (SSH: Up)
Total nodes: 1
1. starcluster ebsimage i-d9eb1c8f GE_SGE_NOInstanceStore

> > > Removing private data...
> > > Creating EBS image...
> > > Waiting for AMI ami-c1ce8093 to become available...!!! ERROR - Error occurred while creating image
> > > Traceback (most recent call last):
> > >   File "/usr/lib/python2.7/site-packages/StarCluster-0.9999-py2.7.egg/starcluster/cli.py", line 255, in main
> > >     sc.execute(args)
> > >   File "/usr/lib/python2.7/site-packages/StarCluster-0.9999-py2.7.egg/starcluster/commands/ebsimage.py", line 69, in execute
> > >     *_self.specified_options_dict)
> > >   File "/usr/lib/python2.7/site-packages/StarCluster-0.9999-py2.7.egg/starcluster/awsutils.py", line 768, in create_ebs_image
> > >     return icreator.create_image(size=root_vol_size)
> > >   File "<string>", line 2, in create_image
> > >   File "/usr/lib/python2.7/site-packages/StarCluster-0.9999-py2.7.egg/starcluster/utils.py", line 87, in wrap_f
> > >     res = func(_arg, **kargs)
> > >   File "/usr/lib/python2.7/site-packages/StarCluster-0.9999-py2.7.egg/starcluster/image.py", line 211, in create_image
> > >     return self._create_image_from_ebs(size)
> > >   File "/usr/lib/python2.7/site-packages/StarCluster-0.9999-py2.7.egg/starcluster/image.py", line 231, in _create_image_from_ebs
> > >     snap = img.block_device_mapping['/dev/sda1'].snapshot_id
> > > KeyError: '/dev/sda1'

!!! ERROR - Oops! Looks like you've found a bug in StarCluster
!!! ERROR - Crash report written to: /home/aravindan/.starcluster/logs/crash-report-6065.txt
!!! ERROR - Please remove any sensitive data from the crash report
!!! ERROR - and submit it to starcluster@mit.edu
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
  File "/usr/lib/python2.7/site-packages/ssh-1.7.13-py2.7.egg/ssh/transport.py", line 1602, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'

**Comment by jtriley** [comment]
@aaravindanarun Thanks for reporting. FYI the AMI you created (ami-c1ce8093) should work fine. The ebsimage failed at the step where it simply waits for the snapshot to finish before returning given that the AMI isnt really ready until the snapshot's status is at 100%. 

With that said there was an issue here fetching the block device mapping for some reason - will likely need to update the code to retry in case of failure. Can you please attach the crash report that was generated? From the output above it should be at: /home/aravindan/.starcluster/logs/crash-report-6065.txt

**Comment by aaravindanarun** [comment]
Thanks for reply,  I would like to inform my Root_volume is not /dev/sda1, 

My root Volume name is /dev/sda --> but starcluster dedicated /dev/sda1 wrong.

---------- CRASH DETAILS ----------
COMMAND: starcluster ebsimage i-d9eb1c8f GE_SGE_NoInstanceStore
2013-06-11 10:38:33,493 PID: 6065 config.py:551 - DEBUG - Loading config
2013-06-11 10:38:33,494 PID: 6065 config.py:118 - DEBUG - Loading file: /home/aravindan/.starcluster/config
2013-06-11 10:38:33,517 PID: 6065 awsutils.py:54 - DEBUG - creating self._conn w/ connection_authenticator kwargs = {'proxy_user': None, 'proxy_pass': None, 'proxy_port': None, 'proxy': None, 'is_secure': True, 'path': '/', 'region': RegionInfo:ap-southeast-1, 'port': None}
2013-06-11 10:38:34,051 PID: 6065 __init__.py:75 - DEBUG - loading private key /home/aravindan/.ssh/starcluster.rsa
2013-06-11 10:38:34,057 PID: 6065 **init**.py:167 - DEBUG - Using private key /home/aravindan/.ssh/starcluster.rsa (rsa)
2013-06-11 10:38:34,057 PID: 6065 image.py:40 - INFO - Removing private data...
2013-06-11 10:38:34,060 PID: 6065 **init**.py:97 - DEBUG - connecting to host ec2-175-41-168-194.ap-southeast-1.compute.amazonaws.com on port 22 as user root
2013-06-11 10:38:40,831 PID: 6065 **init**.py:186 - DEBUG - creating sftp connection
2013-06-11 10:38:43,989 PID: 6065 image.py:225 - INFO - Creating EBS image...
2013-06-11 10:38:44,188 PID: 6065 image.py:229 - INFO - Waiting for AMI ami-c1ce8093 to become available...
2013-06-11 10:38:44,337 PID: 6065 image.py:214 - ERROR - Error occurred while creating image
2013-06-11 10:38:44,345 PID: 6065 cli.py:287 - DEBUG - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/StarCluster-0.9999-py2.7.egg/starcluster/cli.py", line 255, in main
    sc.execute(args)
  File "/usr/lib/python2.7/site-packages/StarCluster-0.9999-py2.7.egg/starcluster/commands/ebsimage.py", line 69, in execute
    *_self.specified_options_dict)
  File "/usr/lib/python2.7/site-packages/StarCluster-0.9999-py2.7.egg/starcluster/awsutils.py", line 768, in create_ebs_image
    return icreator.create_image(size=root_vol_size)
  File "<string>", line 2, in create_image
  File "/usr/lib/python2.7/site-packages/StarCluster-0.9999-py2.7.egg/starcluster/utils.py", line 87, in wrap_f
    res = func(_arg, **kargs)
  File "/usr/lib/python2.7/site-packages/StarCluster-0.9999-py2.7.egg/starcluster/image.py", line 211, in create_image
    return self._create_image_from_ebs(size)
  File "/usr/lib/python2.7/site-packages/StarCluster-0.9999-py2.7.egg/starcluster/image.py", line 231, in _create_image_from_ebs
    snap = img.block_device_mapping['/dev/sda1'].snapshot_id
KeyError: '/dev/sda1'

---------- SYSTEM INFO ----------
StarCluster: 0.9999
Python: 2.7.3 (default, Apr 30 2012, 21:18:10)  [GCC 4.7.0 20120416 (Red Hat 4.7.0-2)]
Platform: Linux-3.3.4-5.fc17.i686.PAE-i686-with-fedora-17-Beefy_Miracle
boto: 2.3.0
ssh: 1.7.13
Crypto: 2.6
jinja2: 2.6
decorator: 3.3.1

**Comment by jtriley** [comment]
@aaravindanarun FYI, /dev/sda1 is what the root device _should_ be:

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/block-device-mapping-concepts.html#ami-block-device-mapping

(see "Specifying a Block Device Mapping")

In _any_ case the AMI's root device name needs to match the real root device (in your case /dev/sda) in order for any EC2 tool to inspect what the real root device is without completely guessing which is what starcluster ultimately has to do in this case.

**Comment by aaravindanarun** [comment]
Thanks for reply, Thanks for providing Amazon AWS reference link.

I am tested switch root device name from /dev/sda to /dev/sda1 - without update any patch the starcluster was working stop and terminate running instance on CentOS AMI.

I assumed CentOS Marketplace AMI root device name is /dev/sda.
An idea to switch the root device from /dev/sda to /dev/sda1 on using CentOS Marketplace AMI. It's default root device value in Amazon AWS.

Steps:
1. Launch an instance from 'CentOS 6.3 Market place' AMI. (actually in my case ami-34226166 in Singapore Region)
2. Edit /boot/grub/grub.conf file, /dev/sda to /dev/sda1.
3. Create a snapshot of root device EBS volume.
4. Register an AMI image with the snapshot with the following command,
   ec2-register --region XX-XXXXXXXX-X -n 'XXXXX' -d XXXXX --root-device-name /dev/sda1 -b /dev/sda1=snap-xxxxxxxx -a x86_64 --kernel aki-xxxxxxxx

Launch created AMI using starcluster, then try with stop / terminate command:

It's Working for me.

**Comment by jtriley** [comment]
Closed by 75b9252
