### ISSUE TITLE
Failure to terminate spot instance cluster on ap-southeast-1

### ISSUE THREAD

**Issue by ogrisel** [jtriley/StarCluster#261]
I am not sure whether this is related to the use of spot instance of not, but I get the following error:

```
!!! ERROR - UnsupportedOperation: The functionality you requested is not available in this region.
Traceback (most recent call last):
  File "/Users/ogrisel/code/StarCluster/starcluster/cli.py", line 257, in main
    sc.execute(args)
  File "/Users/ogrisel/code/StarCluster/starcluster/commands/terminate.py", line 87, in execute
    self.terminate(cluster_name, force=self.opts.force)
  File "/Users/ogrisel/code/StarCluster/starcluster/commands/terminate.py", line 75, in terminate
    self._terminate_manually(cl)
  File "/Users/ogrisel/code/StarCluster/starcluster/commands/terminate.py", line 59, in _terminate_manually
    cl.terminate_cluster(force=True)
  File "/Users/ogrisel/code/StarCluster/starcluster/cluster.py", line 1414, in terminate_cluster
    pg = self.ec2.get_placement_group_or_none(self._security_group)
  File "/Users/ogrisel/code/StarCluster/starcluster/awsutils.py", line 308, in get_placement_group_or_none
    return self.get_placement_group(name)
  File "/Users/ogrisel/code/StarCluster/starcluster/awsutils.py", line 295, in get_placement_group
    groupname})[0]
  File "/Users/ogrisel/code/StarCluster/starcluster/awsutils.py", line 290, in get_placement_groups
    return self.conn.get_all_placement_groups(filters=filters)
  File "/usr/local/lib/python2.7/site-packages/boto/ec2/connection.py", line 3178, in get_all_placement_groups
    [('item', PlacementGroup)], verb='POST')
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1049, in get_list
    raise self.ResponseError(response.status, response.reason, body)
EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>UnsupportedOperation</Code><Message>The functionality you requested is not available in this region.</Message></Error></Errors><RequestID>2cce6da5-e6e7-4078-83c4-8b94c5b3c2a9</RequestID></Response>
```

**Comment by jtriley** [comment]
Thanks for reporting fixing this now.

**Comment by ogrisel** [comment]
Thanks!
