### ISSUE TITLE
bug in 0.92rc1 setup.py breaks easy_install

### ISSUE THREAD

**Issue by jtriley** [jtriley/StarCluster#27]
From Adam Marsh on the mailing list:

When I run the install routine for the 0.92rc1 version of SC, it aborts with the following error message:
ImportError: No module named starcluster

Full output from the command "sudo easy_install StarCluster":

$ sudo easy_install StarCluster
Searching for StarCluster
Reading http://pypi.python.org/simple/StarCluster/
Reading http://web.mit.edu/starcluster
Best match: StarCluster 0.92rc1
Downloading http://pypi.python.org/packages/source/S/StarCluster/StarCluster-0.92rc1.tar.gz#md5=0e2fadfa011de41bf6a6868bc37c61ed
Processing StarCluster-0.92rc1.tar.gz
Running StarCluster-0.92rc1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-_L48LL/StarCluster-0.92rc1/egg-dist-tmp-ZZxqNG
Traceback (most recent call last):
  File "/usr/bin/easy_install", line 9, in <module>
    load_entry_point('distribute==0.6.10', 'console_scripts', 'easy_install')()
  File "/usr/lib/python2.6/dist-packages/setuptools/command/easy_install.py", line 1760, in main
    with_ei_usage(lambda:
  File "/usr/lib/python2.6/dist-packages/setuptools/command/easy_install.py", line 1741, in with_ei_usage
    return f()
  File "/usr/lib/python2.6/dist-packages/setuptools/command/easy_install.py", line 1764, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "/usr/lib/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.6/dist-packages/setuptools/command/easy_install.py", line 254, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.6/dist-packages/setuptools/command/easy_install.py", line 489, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.6/dist-packages/setuptools/command/easy_install.py", line 519, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.6/dist-packages/setuptools/command/easy_install.py", line 698, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.6/dist-packages/setuptools/command/easy_install.py", line 975, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.6/dist-packages/setuptools/command/easy_install.py", line 964, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.6/dist-packages/setuptools/sandbox.py", line 29, in run_setup
    lambda: execfile(
  File "/usr/lib/python2.6/dist-packages/setuptools/sandbox.py", line 70, in run
    return func()
  File "/usr/lib/python2.6/dist-packages/setuptools/sandbox.py", line 31, in <lambda>
    {'__file__':setup_script, '**name**':'**main**'}
  File "setup.py", line 5, in <module>
ImportError: No module named starcluster

**Comment by jtriley** [comment]
previous commit didn't really fix it on pypi
