### ISSUE TITLE
Unable to add node

### ISSUE THREAD

**Issue by mktrost** [jtriley/StarCluster#286]
We are getting crash reports when we try to add some nodes.

Here is the information from the crash report.  Let me know if you need more information.

---------- SYSTEM INFO ----------
StarCluster: 0.94
Python: 2.7.3 (default, Apr 10 2013, 06:20:15)  [GCC 4.6.3]
Platform: Linux-3.2.23-x86_64-with-Ubuntu-12.04-precise
boto: 2.10.0
paramiko: 1.11.0
Crypto: 2.4.1

---------- CRASH DETAILS ----------
Command: starcluster addnode -n 1 63

....LET ME KNOW IF YOU NEED THE INFO THAT WAS HERE....

<pre>
2013-08-26 16:24:48,296 PID: 10534 utils.py:117 - INFO - Waiting for cluster to come up took 2.020 mins
2013-08-26 16:24:48,296 PID: 10534 cluster.py:907 - DEBUG - Adding node(s): ['node001']
2013-08-26 16:24:48,462 PID: 10534 cluster.py:710 - DEBUG - existing nodes: {u'i-fe7d9cc9': <Node: node001 (i-fe7d9cc9)>, u'i-a8b7859c': <Node: master (i-a8b7859c)>}
2013-08-26 16:24:48,463 PID: 10534 cluster.py:713 - DEBUG - updating existing node i-a8b7859c in self._nodes
2013-08-26 16:24:48,464 PID: 10534 cluster.py:713 - DEBUG - updating existing node i-fe7d9cc9 in self._nodes
2013-08-26 16:24:48,464 PID: 10534 cluster.py:726 - DEBUG - returning self._nodes = [<Node: master (i-a8b7859c)>, <Node: node001 (i-fe7d9cc9)>]
2013-08-26 16:24:48,627 PID: 10534 cluster.py:710 - DEBUG - existing nodes: {u'i-fe7d9cc9': <Node: node001 (i-fe7d9cc9)>, u'i-a8b7859c': <Node: master (i-a8b7859c)>}
2013-08-26 16:24:48,628 PID: 10534 cluster.py:713 - DEBUG - updating existing node i-a8b7859c in self._nodes
2013-08-26 16:24:48,629 PID: 10534 cluster.py:713 - DEBUG - updating existing node i-fe7d9cc9 in self._nodes
2013-08-26 16:24:48,629 PID: 10534 cluster.py:726 - DEBUG - returning self._nodes = [<Node: master (i-a8b7859c)>, <Node: node001 (i-fe7d9cc9)>]
2013-08-26 16:24:48,630 PID: 10534 cluster.py:1557 - INFO - Running plugin starcluster.clustersetup.DefaultClusterSetup
2013-08-26 16:24:48,630 PID: 10534 clustersetup.py:121 - INFO - Configuring hostnames...
2013-08-26 16:24:48,636 PID: 10534 threadpool.py:168 - DEBUG - unfinished_tasks = 1
2013-08-26 16:24:48,998 PID: 10534 __init__.py:538 - DEBUG - executing remote command: source /etc/profile && hostname -F /etc/hostname
2013-08-26 16:24:49,108 PID: 10534 __init__.py:562 - DEBUG - output of 'source /etc/profile && hostname -F /etc/hostname':

2013-08-26 16:24:49,638 PID: 10534 clustersetup.py:247 - INFO - Configuring /etc/hosts on each node
2013-08-26 16:24:49,640 PID: 10534 threadpool.py:168 - DEBUG - unfinished_tasks = 2
2013-08-26 16:24:49,978 PID: 10534 __init__.py:296 - DEBUG - new /etc/hosts after removing regex (master|node001) matches:
127.0.0.1 localhost

#   Convenient IP address to machines I use
ipaddress  name1 d
ipaddress  name2 w

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

2013-08-26 16:24:49,988 PID: 10534 __init__.py:296 - DEBUG - new /etc/hosts after removing regex (master|node001) matches:
127.0.0.1 localhost

#   Convenient IP address to machines I use
ipaddress  name1 d
ipaddress  name2 w

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

2013-08-26 16:24:50,642 PID: 10534 threadpool.py:168 - DEBUG - unfinished_tasks = 2
2013-08-26 16:24:51,643 PID: 10534 threadpool.py:168 - DEBUG - unfinished_tasks = 2
2013-08-26 16:24:52,645 PID: 10534 node.py:660 - INFO - Configuring NFS exports path(s):
/home /usr/local/gotcloud
2013-08-26 16:24:52,730 PID: 10534 cluster.py:1567 - ERROR - Error occured while running plugin 'starcluster.clustersetup.DefaultClusterSetup':
2013-08-26 16:24:52,731 PID: 10534 cli.py:307 - ERROR - Unhandled exception occured
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.94-py2.7.egg/starcluster/cli.py", line 274, in main
    sc.execute(args)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.94-py2.7.egg/starcluster/commands/addnode.py", line 137, in execute
    no_create=self.opts.no_create)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.94-py2.7.egg/starcluster/cluster.py", line 184, in add_nodes
    no_create=no_create)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.94-py2.7.egg/starcluster/cluster.py", line 910, in add_nodes
    self.run_plugins(method_name="on_add_node", node=node)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.94-py2.7.egg/starcluster/cluster.py", line 1533, in run_plugins
    self.run_plugin(plug, method_name=method_name, node=node)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.94-py2.7.egg/starcluster/cluster.py", line 1558, in run_plugin
    func(*args)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.94-py2.7.egg/starcluster/clustersetup.py", line 426, in on_add_node
    self._setup_nfs(nodes=[node], start_server=False)
  File "<string>", line 2, in _setup_nfs
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.94-py2.7.egg/starcluster/utils.py", line 111, in wrap_f
    res = func(*arg, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.94-py2.7.egg/starcluster/clustersetup.py", line 367, in _setup_nfs
    master.export_fs_to_nodes(nodes, export_paths)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.94-py2.7.egg/starcluster/node.py", line 662, in export_fs_to_nodes
    etc_exports = self.ssh.remote_file('/etc/exports', 'r')
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.94-py2.7.egg/starcluster/sshutils/__init__.py", line 308, in remote_file
    rfile = self.sftp.open(file, mode)
  File "/usr/local/lib/python2.7/dist-packages/paramiko-1.11.0-py2.7.egg/paramiko/sftp_client.py", line 245, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
  File "/usr/local/lib/python2.7/dist-packages/paramiko-1.11.0-py2.7.egg/paramiko/sftp_client.py", line 689, in _request
    return self._read_response(num)
  File "/usr/local/lib/python2.7/dist-packages/paramiko-1.11.0-py2.7.egg/paramiko/sftp_client.py", line 736, in _read_response
    self._convert_status(msg)
  File "/usr/local/lib/python2.7/dist-packages/paramiko-1.11.0-py2.7.egg/paramiko/sftp_client.py", line 762, in _convert_status
    raise IOError(errno.ENOENT, text)
IOError: [Errno 2] No such file
</pre>

**Comment by jtriley** [comment]
@mktrost Which AMI are you using?

**Comment by mktrost** [comment]
We are using: ami-cd861bfd

Possibly relevant: The first time we tried add node we did a ctrl-c immediately after it began, then it failed.  Then terminated the cluster and tried again and again and it still fails.

**Comment by jtriley** [comment]
I still need to double check but this seems like a custom AMI. I can fix the "no such file" error but if NFS is not installed it will fail later as well. StarCluster currently relies on it being in the AMI.

**Comment by mktrost** [comment]
Oh, so sorry.  You are a correct, that was the wrong AMI.  We accidentally copied a bad one that we were testing with in there.  Thanks for pointing this out to us, and sorry for spending your time on our mistake.

**Comment by jtriley** [comment]
@mktrost No problem at all glad we figured out the issue!
