### ISSUE TITLE
Creating a new S3 image of AMI fails

### ISSUE THREAD

**Issue by nkrumm** [jtriley/StarCluster#300]
Hi,

Thanks for creating starcluster. I have had success in the past with creating a new AMI via s3image from the public starcluster AMIs... however, now this seems to fail (even with what I think are the same steps). Specifically, `s3image` fails with the error:

``` bash
starcluster start -o -s 1 -b 0.50 -i m1.large -n ami-765b3e1f imagehost
[ I configure the machine ]

starcluster s3image i-cb7f4cb3 asd_jre_default asdjre
[see log here: http://pastebin.com/7iWgGmX3]
Bundle upload completed.
>>> _upload_image took 2.229 mins
!!! ERROR - InvalidManifest: Invalid block device mapping: Invalid device name 'xvdal'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/starcluster/cli.py", line 274, in main
    sc.execute(args)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/starcluster/commands/s3image.py", line 89, in execute
    **self.specified_options_dict)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/starcluster/awsutils.py", line 862, in create_s3_image
    return icreator.create_image()
  File "<string>", line 2, in create_image
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/starcluster/utils.py", line 111, in wrap_f
    res = func(*arg, **kargs)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/starcluster/image.py", line 135, in create_image
    ami_id = self._register_image()
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/starcluster/image.py", line 198, in _register_image
    architecture=config_dict.get('arch'),
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/starcluster/awsutils.py", line 488, in register_image
    block_device_map=block_device_map)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/boto/ec2/connection.py", line 288, in register_image
    rs = self.get_object('RegisterImage', params, ResultSet, verb='POST')
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/boto/connection.py", line 1096, in get_object
    raise self.ResponseError(response.status, response.reason, body)
EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidManifest</Code><Message>Invalid block device mapping: Invalid device name 'xvdal'</Message></Error></Errors><RequestID>d9edffaf-7e65-4c3c-b2a3-e4c26dfccf0c</RequestID></Response>
```

After this, the imagehost instance becomes unaccessible to SSH (returning simply "Connection closed by 54.242.##.###". 

In the s3 bucket, I see a manifest file and the uploaded *.part files.

A complete log of the s3image command: http://pastebin.com/7iWgGmX3

Any help here would be hugely appreciated. I've looked around on the internet and have found one similar bug report here: https://github.com/ContinuumIO/anaconda-ec2/issues/7

**Comment by jtriley** [comment]
@nkrumm Thanks for reporting. Looking into this now. As a workaround the ebsimage command works well and is the command most folks are using these days given that EBS images are preferred.

**Comment by jtriley** [comment]
@nkrumm Also, you should be able to reboot the instance using:

```
$ starcluster restart imagehost
```

This should reconfigure the ssh keys and enable your SSH login again.

**Comment by jtriley** [comment]
@nkrumm My comment to ContinuumIO/anaconda-ec2#7 applies here as well.

**Comment by nkrumm** [comment]
thanks, @jtriley. looking forward to the fix-- let me know if i can help in any way.
