### ISSUE TITLE
createimage can't import iptools.ipv4

### ISSUE THREAD

**Issue by twiecki** [jtriley/StarCluster#315]
```
Traceback (most recent call last):
  File "/home/wiecki/working/projects/quant/StarCluster/starcluster/cli.py", line 274, in main
    sc.execute(args)
  File "/home/wiecki/working/projects/quant/StarCluster/starcluster/commands/s3image.py", line 89, in execute
    **self.specified_options_dict)
  File "/home/wiecki/working/projects/quant/StarCluster/starcluster/awsutils.py", line 925, in create_s3_image
    remove_image_files=remove_image_files)
  File "/home/wiecki/working/projects/quant/StarCluster/starcluster/image.py", line 93, in __init__
    if not utils.is_valid_bucket_name(name):
  File "/home/wiecki/working/projects/quant/StarCluster/starcluster/utils.py", line 163, in is_valid_bucket_name
    if iptools.ipv4.validate_ip(bucket_name):
AttributeError: 'module' object has no attribute 'ipv4'
```

**Comment by twiecki** [comment]
This is with `iptools==0.6.1`.

**Comment by twiecki** [comment]
Oops, had a stale iptools.pyc hanging around.

**Comment by jtriley** [comment]
@twiecki I think you need to run `python setup.py develop` again or whatever command you used to install StarCluster. Works for me in a fresh virtualenv with iptools 0.6.1 on both python 2.6 and 2.7:

```
% python -c "import iptools; print iptools.__version__"
0.6.1

% python -c "import iptools; print iptools.ipv4.validate_ip('mybucket')"
False

% starcluster sh
[1]> utils.is_valid_bucket_name('blah')
[1]> True
```

**Comment by jtriley** [comment]
Ha! You closed this _just_ before I posted that. Thanks for double checking!

**Comment by twiecki** [comment]
haha, thanks for the quick reply!

**Comment by twiecki** [comment]
While I have you, SC asks me for
`!!! ERROR - No certificate file (pem) specified in config (EC2_CERT)`

Pretty sure I didn't need that before -- did that change? I'm also not quite sure what it's asking for.

**Comment by twiecki** [comment]
Ah, the options are now `ebsimage` and `s3image`.
