### ISSUE TITLE
`addnode` fails in VPC

### ISSUE THREAD

**Issue by delagoya** [jtriley/StarCluster#342]
``` bash
ubuntu@ip-10-0-0-29:~/test$ starcluster addnode   smallcluster
StarCluster - (http://star.mit.edu/cluster) (v. 0.9999)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

>>> Launching node(s): node003
!!! ERROR - InvalidParameterCombination: VPC security groups may not be used for a non-VPC launch
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cli.py", line 274, in main
    sc.execute(args)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/commands/addnode.py", line 137, in execute
    no_create=self.opts.no_create)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cluster.py", line 189, in add_nodes
    no_create=no_create)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cluster.py", line 950, in add_nodes
    spot_bid=spot_bid)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cluster.py", line 887, in create_nodes
    resvs.append(self.ec2.request_instances(image_id, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/awsutils.py", line 481, in request_instances
    **shared_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/awsutils.py", line 570, in run_instances
    return self.conn.run_instances(image_id, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 912, in run_instances
    verb='POST')
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1139, in get_object
    raise self.ResponseError(response.status, response.reason, body)
EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterCombination</Code><Message>VPC security groups may not be used for a non-VPC launch</Message></Error></Errors><RequestID>ee0c75d7-d1e4-48a1-aa67-394d2ac3ad8b</RequestID></Response>
```

Using commit SHA: 613822af404f77496996a556d0d298e78900e62c

**Comment by jtriley** [comment]
@delagoya Thanks for reporting. I'm looking into this and #341 now.

**Comment by jtriley** [comment]
@delagoya This is fixed in the latest develop branch but only for clusters created with the fix - you'll have to relaunch any clusters created prior to the fix.
