### ISSUE TITLE
Volume Creator Errors with no Default VPC

### ISSUE THREAD

**Issue by dave-fl** [jtriley/StarCluster#389]
The volume creator command should be sensitive to the subnet_id parameter as it is possible that IAM permissions have been defined to enforce that a user can only launch within a specific subnet.  Additionally it is possible that the user does not have a default VPC.  

ubuntu@ip-10-0-0-31:~$ starcluster createvolume --detach-volume 1 us-east-1c
StarCluster - (http://star.mit.edu/cluster) (v. 0.95.4)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

> > > No keypair specified, picking one from config...
> > > Using keypair: mykey
> > > Creating security group @sc-volumecreator...
> > > !!! ERROR - Failed to create new volume
> > > Traceback (most recent call last):
> > >   File "/usr/local/lib/python2.7/dist-packages/starcluster/volume.py", line 284, in create
> > >     instance = self._request_instance(volume_zone)
> > >   File "/usr/local/lib/python2.7/dist-packages/starcluster/volume.py", line 94, in _request_instance
> > >     (self.cluster_group.name, zone))
> > >   File "/usr/local/lib/python2.7/dist-packages/starcluster/cluster.py", line 655, in cluster_group
> > >     vpc_id=vpc_id)
> > >   File "/usr/local/lib/python2.7/dist-packages/starcluster/awsutils.py", line 296, in create_group
> > >     sg = self.conn.create_security_group(name, description, vpc_id=vpc_id)
> > >   File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 2956, in create_security_group
> > >     SecurityGroup, verb='POST')
> > >   File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1177, in get_object
> > >     raise self.ResponseError(response.status, response.reason, body)
> > > EC2ResponseError: EC2ResponseError: 400 Bad Request
> > > <?xml version="1.0" encoding="UTF-8"?>
> > > <Response><Errors><Error><Code>VPCIdNotSpecified</Code><Message>No default VPC for this user</Message></Error></Errors><RequestID>b6636406-3e96-49c2-b9ed-5cd372161815</RequestID></Response>
> > > !!! ERROR - VPCIdNotSpecified: No default VPC for this user

**Comment by cjw85** [comment]
I second this. I've just started looking into StarCluster today, and beginning to see how great it could be. Then I ran into this problem due to IAM permissions meaning I can only launch instances within a specific subnet.

**Comment by cjw85** [comment]
Seems like an easy fix, I cut and paste the option code from starcluster/commands/start.py to starcluster/commands/createvolume.py and a volume in now being created.
