### ISSUE TITLE
Issue creating cluster

### ISSUE THREAD

**Issue by garnaout** [jtriley/StarCluster#405]
I get the folllowing error when I try to create an EBS vol using starcluster. Even when creating the volume outside starcluster, I still get the same error when I try to create the cluster after

!!! ERROR - Connection error:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/StarCluster-0.95.5-py2.6.egg/starcluster/cli.py", line 274, in main
    sc.execute(args)
  File "/usr/lib/python2.6/site-packages/StarCluster-0.95.5-py2.6.egg/starcluster/commands/createvolume.py", line 131, in execute
    zone = self.ec2.get_zone(zone).name
  File "/usr/lib/python2.6/site-packages/StarCluster-0.95.5-py2.6.egg/starcluster/awsutils.py", line 1018, in get_zone
    return self.get_zones(filters={'zone-name': zone})[0]
  File "/usr/lib/python2.6/site-packages/StarCluster-0.95.5-py2.6.egg/starcluster/awsutils.py", line 1010, in get_zones
    return self.conn.get_all_zones(filters=filters)
  File "/usr/lib/python2.6/site-packages/boto-2.29.1-py2.6.egg/boto/ec2/connection.py", line 1725, in get_all_zones
    [('item', Zone)], verb='POST')
  File "/usr/lib/python2.6/site-packages/boto-2.29.1-py2.6.egg/boto/connection.py", line 1143, in get_list
    response = self.make_request(action, params, path, verb)
  File "/usr/lib/python2.6/site-packages/boto-2.29.1-py2.6.egg/boto/connection.py", line 1089, in make_request
    return self._mexe(http_request)
  File "/usr/lib/python2.6/site-packages/boto-2.29.1-py2.6.egg/boto/connection.py", line 922, in _mexe
    request.body, request.headers)
  File "/usr/lib64/python2.6/httplib.py", line 910, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.6/httplib.py", line 947, in _send_request
    self.endheaders()
  File "/usr/lib64/python2.6/httplib.py", line 904, in endheaders
    self._send_output()
  File "/usr/lib64/python2.6/httplib.py", line 776, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.6/httplib.py", line 735, in send
    self.connect()
  File "/usr/lib/python2.6/site-packages/boto-2.29.1-py2.6.egg/boto/https_connection.py", line 111, in connect
    sock.connect((self.host, self.port))
  File "<string>", line 1, in connect
timeout: timed out
!!! ERROR - Check your internet connection?

**Comment by garnaout** [comment]
note that the initial error (that I have never seen before) was that "NO KEY PAIR WAS SPECIFIED - USING Keypair form config ERROR - no keypairs found in regio us-east-1" 

I got rid of that by adding my [aws info] in the config

**Comment by jtriley** [comment]
@garnaout That initial error would be solved by adding a [keypair] section not [aws info]. The error you pasted above indicates boto can't connect to AWS (ie it times out while trying to connect). Double check your internet connection and firewall. Also, what region are you using? Have you tried switching regions to see if you get the same error?
