### ISSUE TITLE
Issue with Visualizing and Date Parsing

### ISSUE THREAD

**Issue by cancan101** [jtriley/StarCluster#439]
```
>>> Waiting for cluster to stabilize...
!!! ERROR - Unhandled exception occured
Traceback (most recent call last):
  File "/Users/alex/git/StarCluster/starcluster/cli.py", line 274, in main
    sc.execute(args)
  File "/Users/alex/git/StarCluster/starcluster/commands/loadbalance.py", line 115, in execute
    lb.run(cluster)
  File "/Users/alex/git/StarCluster/starcluster/balancers/sge/__init__.py", line 643, in run
    self.visualizer.graph_all()
  File "/Users/alex/git/StarCluster/starcluster/balancers/sge/visualizer.py", line 71, in graph_all
    self.read()
  File "/Users/alex/git/StarCluster/starcluster/balancers/sge/visualizer.py", line 47, in read
    a = [datetime.strptime(parts[0], '%Y-%m-%d %H:%M:%S.%f'),
  File "/usr/local/Cellar/python/2.7.7_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_strptime.py", line 328, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: +00:00
```

Caused by:

```
In [11]:  str(datetime.datetime.utcnow().replace(tzinfo=iso8601.iso8601.UTC))
Out[11]: '2014-09-10 05:37:41.179948+00:00'
```

not being parsed correctly by: `%Y-%m-%d %H:%M:%S.%f%`

**Comment by xanderdunn** [comment]
I also get this crash when I run `starcluster loadbalance` with the `-p`.  It works fine without `-p`.
