### ISSUE TITLE
InvalidParameterCombination error with Volume Type = General Purpose (SSD) AMIs

### ISSUE THREAD

**Issue by hughamacmullaniv** [jtriley/StarCluster#448]
Hi StarCluster Team:

When using an AMI with volume type = General Purpose (SSD), I get (in debug.log):

2014-09-25 11:08:08,984 PID: 8599 awsutils.py:497 - DEBUG - Forcing delete_on_termination for AMI: ami-083b8e60
2014-09-25 11:08:09,120 PID: 8599 cli.py:277 - ERROR - InvalidParameterCombination: The parameter iops is not supported for gp2 volumes.
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/starcluster/cli.py", line 274, in main
    sc.execute(args)
  File "/usr/lib/python2.6/site-packages/starcluster/commands/start.py", line 244, in execute
    validate_running=validate_running)
  File "/usr/lib/python2.6/site-packages/starcluster/cluster.py", line 1628, in start
    return self._start(create=create, create_only=create_only)
  File "<string>", line 2, in _start
  File "/usr/lib/python2.6/site-packages/starcluster/utils.py", line 112, in wrap_f
    res = func(_arg, *_kargs)
  File "/usr/lib/python2.6/site-packages/starcluster/cluster.py", line 1643, in _start
    self.create_cluster()
  File "/usr/lib/python2.6/site-packages/starcluster/cluster.py", line 1163, in create_cluster
    self._create_flat_rate_cluster()
  File "/usr/lib/python2.6/site-packages/starcluster/cluster.py", line 1185, in _create_flat_rate_cluster
    force_flat=True)[0]
  File "/usr/lib/python2.6/site-packages/starcluster/cluster.py", line 966, in create_nodes
    resvs.append(self.ec2.request_instances(image_id, *_kwargs))
  File "/usr/lib/python2.6/site-packages/starcluster/awsutils.py", line 525, in request_instances
    *_shared_kwargs)
  File "/usr/lib/python2.6/site-packages/starcluster/awsutils.py", line 626, in run_instances
    return self.conn.run_instances(image_id, **kwargs)
  File "/usr/lib/python2.6/site-packages/boto/ec2/connection.py", line 975, in run_instances
    verb='POST')
  File "/usr/lib/python2.6/site-packages/boto/connection.py", line 1188, in get_object
    raise self.ResponseError(response.status, response.reason, body)
EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterCombination</Code><Message>The parameter iops is not supported for gp2 volumes.</Message></Error></Errors><RequestID>c8306558-f673-4fb6-9ea1-64b4d6fdd1c7</RequestID></Response>

The AMIs in question are clones of fully functional volume type = Magnetic

**Comment by hughamacmullaniv** [comment]
It was pointed out to me that this was already requested in issue #264. Closing.

**Comment by hughamacmullaniv** [comment]
After further consideration, the two issues --volume type selection during volume creation (#264) and this error -- should remain separate. This issue is a bug, the other is a feature request.
