### ISSUE TITLE
No handlers could be found for logger "paramiko.transport"

### ISSUE THREAD

**Issue by cancan101** [jtriley/StarCluster#449]
```
No handlers could be found for logger "paramiko.transport"
!!! ERROR - Error occured while running plugin 'starcluster.clustersetup.DefaultClusterSetup':
!!! ERROR - Unhandled exception occured
Traceback (most recent call last):
  File "/Users/alex/git/StarCluster/starcluster/cli.py", line 274, in main
    sc.execute(args)
  File "/Users/alex/git/StarCluster/starcluster/commands/removenode.py", line 127, in execute
    force=self.opts.force)
  File "/Users/alex/git/StarCluster/starcluster/cluster.py", line 210, in remove_nodes
    terminate=terminate, force=force)
  File "/Users/alex/git/StarCluster/starcluster/cluster.py", line 1087, in remove_nodes
    reverse=True)
  File "/Users/alex/git/StarCluster/starcluster/cluster.py", line 1717, in run_plugins
    self.run_plugin(plug, method_name=method_name, node=node)
  File "/Users/alex/git/StarCluster/starcluster/cluster.py", line 1742, in run_plugin
    func(*args)
  File "/Users/alex/git/StarCluster/starcluster/clustersetup.py", line 407, in on_remove_node
    self._remove_from_known_hosts(node)
  File "/Users/alex/git/StarCluster/starcluster/clustersetup.py", line 397, in _remove_from_known_hosts
    n.remove_from_known_hosts(self._user, [node])
  File "/Users/alex/git/StarCluster/starcluster/node.py", line 595, in remove_from_known_hosts
    self.ssh.remove_lines_from_file(known_hosts_file, regex)
  File "/Users/alex/git/StarCluster/starcluster/sshutils.py", line 310, in remove_lines_from_file
    f.writelines(lines)
  File "/usr/local/lib/python2.7/site-packages/paramiko/file.py", line 359, in writelines
    self.write(line)
  File "/usr/local/lib/python2.7/site-packages/paramiko/file.py", line 330, in write
    self._write_all(data)
  File "/usr/local/lib/python2.7/site-packages/paramiko/file.py", line 447, in _write_all
    count = self._write(data)
  File "/usr/local/lib/python2.7/site-packages/paramiko/sftp_file.py", line 180, in _write
    t, msg = self.sftp._read_response(req)
  File "/usr/local/lib/python2.7/site-packages/paramiko/sftp_client.py", line 681, in _read_response
    raise SSHException('Server connection dropped: %s' % str(e))
SSHException: Server connection dropped: 
```

**Comment by dkoppstein** [comment]
+1. If I try to add a node, it hangs with that error message. 

```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
StarCluster - (http://star.mit.edu/cluster) (v. 0.95.6)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

>>> Launching node(s): node003
Reservation:r-6d3bfc81
>>> Waiting for instances to propagate...
1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
>>> Waiting for node(s) to come up... (updating every 30s)
>>> Waiting for all nodes to be in a 'running' state...
4/4 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
>>> Waiting for SSH to come up on all nodes...
No handlers could be found for logger "paramiko.transport"             |  50%
3/4 |-------------------------------------------------                 |  75%

```

**Comment by mattgiguere** [comment]
@cancan101 @dkoppstein I keep getting that message too. Did either of you come up with a solution?
