### ISSUE TITLE
Crash when placement group delete times out

### ISSUE THREAD

**Issue by kevinbache** [jtriley/StarCluster#460]
I'm getting a crash when terminating a cluster.  It happens every time when node001 (a g2.2xlarge instance; my only worker node) takes too long to shut down and boto times out on deleting the placement group.  I'm running boto 2.32.0.  It happens every time a terminate a cluster and it doesn't matter if I use -f for force or not.

edit: Running `starcluster terminat -f test` after the crash does successfully remove the placement group and security group.

```
$ starcluster terminate -f test
StarCluster - (http://star.mit.edu/cluster) (v. 0.95.5)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

*** WARNING - Ignoring cluster settings due to --force option
Terminate cluster test (y/n)? y
>>> Terminating i-d8a3e2d7
>>> Terminating i-0fa6e700
>>> Running plugin starcluster.plugins.sge.SGEPlugin
>>> Running plugin starcluster.clustersetup.DefaultClusterSetup
>>> Canceling spot instance request: sir-034npl7w
>>> Waiting for cluster to terminate...
>>> Removing placement group: @sc-test
!!! ERROR - Failed to terminate cluster!
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/StarCluster-0.95.5-py2.7.egg/starcluster/commands/terminate.py", line 85, in terminate
    self._terminate_manually(cl)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/StarCluster-0.95.5-py2.7.egg/starcluster/commands/terminate.py", line 76, in _terminate_manually
    cl.terminate_cluster(force=True)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/StarCluster-0.95.5-py2.7.egg/starcluster/cluster.py", line 1591, in terminate_cluster
    self.ec2.delete_group(pg)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/StarCluster-0.95.5-py2.7.egg/starcluster/awsutils.py", line 268, in delete_group
    ret_val = group.delete()
  File "/usr/local/lib/python2.7/site-packages/boto/ec2/placementgroup.py", line 51, in delete
    dry_run=dry_run
  File "/usr/local/lib/python2.7/site-packages/boto/ec2/connection.py", line 4133, in delete_placement_group
    return self.get_status('DeletePlacementGroup', params, verb='POST')
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1210, in get_status
    raise self.ResponseError(response.status, response.reason, body)
EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidPlacementGroup.InUse</Code><Message>The placement group '@sc-test' is in use and may not be deleted.</Message></Error></Errors><RequestID>6533ac3a-0248-4f5d-9704-88742ac168d7</RequestID></Response>
!!! ERROR - InvalidPlacementGroup.InUse: The placement group '@sc-test' is in use and may not be deleted.
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/StarCluster-0.95.5-py2.7.egg/starcluster/cli.py", line 274, in main
    sc.execute(args)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/StarCluster-0.95.5-py2.7.egg/starcluster/commands/terminate.py", line 101, in execute
    self.terminate(cluster_name, force=self.opts.force)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/StarCluster-0.95.5-py2.7.egg/starcluster/commands/terminate.py", line 85, in terminate
    self._terminate_manually(cl)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/StarCluster-0.95.5-py2.7.egg/starcluster/commands/terminate.py", line 76, in _terminate_manually
    cl.terminate_cluster(force=True)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/StarCluster-0.95.5-py2.7.egg/starcluster/cluster.py", line 1591, in terminate_cluster
    self.ec2.delete_group(pg)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/StarCluster-0.95.5-py2.7.egg/starcluster/awsutils.py", line 268, in delete_group
    ret_val = group.delete()
  File "/usr/local/lib/python2.7/site-packages/boto/ec2/placementgroup.py", line 51, in delete
    dry_run=dry_run
  File "/usr/local/lib/python2.7/site-packages/boto/ec2/connection.py", line 4133, in delete_placement_group
    return self.get_status('DeletePlacementGroup', params, verb='POST')
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1210, in get_status
    raise self.ResponseError(response.status, response.reason, body)
EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidPlacementGroup.InUse</Code><Message>The placement group '@sc-test' is in use and may not be deleted.</Message></Error></Errors><RequestID>6533ac3a-0248-4f5d-9704-88742ac168d7</RequestID></Response>
```

**Comment by cancan101** [comment]
See #411

**Comment by kevinbache** [comment]
Closing as redundant.
