### ISSUE TITLE
paramiko raising EOFError

### ISSUE THREAD

**Issue by cancan101** [jtriley/StarCluster#470]
``` pytb
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.7_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/Cellar/python/2.7.7_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/StarCluster-0.95.5-py2.7.egg/starcluster/sshutils.py", line 639, in close
    self._sftp.close()
  File "/usr/local/lib/python2.7/site-packages/paramiko/sftp_client.py", line 133, in close
    self.sock.close()
  File "/usr/local/lib/python2.7/site-packages/paramiko/channel.py", line 556, in close
    self.transport._send_user_message(m)
  File "/usr/local/lib/python2.7/site-packages/paramiko/transport.py", line 1309, in _send_user_message
    self._send_message(data)
  File "/usr/local/lib/python2.7/site-packages/paramiko/transport.py", line 1289, in _send_message
    self.packetizer.send_message(data)
  File "/usr/local/lib/python2.7/site-packages/paramiko/packet.py", line 308, in send_message
    self.write_all(out)
  File "/usr/local/lib/python2.7/site-packages/paramiko/packet.py", line 258, in write_all
    raise EOFError()
EOFError
```

**Comment by cancan101** [comment]
This was an issues with `paramiko==1.14.0`. It does not occur with the newest version.
