### ISSUE TITLE
BotoServerError: BotoServerError: 500 Internal Server Error

### ISSUE THREAD

**Issue by ghost** [jtriley/StarCluster#477]
I'm new to StarCluster. Today I just wanted to add a node to my cluster, and I got the following messages. The same command worked fine for me a few days ago. It says it is an internal server error. Does it mean I cannot do anything on my side until the error is fixed? Thanks.

`Launching node(s): node001
!!! ERROR - InternalError: An internal error has occurred
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/StarCluster-0.95.5-py2.7.egg/starcluster/cli.py", line 274, in main
    sc.execute(args)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/StarCluster-0.95.5-py2.7.egg/starcluster/commands/addnode.py", line 128, in execute
    no_create=self.opts.no_create)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/StarCluster-0.95.5-py2.7.egg/starcluster/cluster.py", line 189, in add_nodes
    no_create=no_create)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/StarCluster-0.95.5-py2.7.egg/starcluster/cluster.py", line 1033, in add_nodes
    spot_bid=spot_bid)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/StarCluster-0.95.5-py2.7.egg/starcluster/cluster.py", line 966, in create_nodes
    resvs.append(self.ec2.request_instances(image_id, **kwargs))
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/StarCluster-0.95.5-py2.7.egg/starcluster/awsutils.py", line 523, in request_instances
    **shared_kwargs)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/StarCluster-0.95.5-py2.7.egg/starcluster/awsutils.py", line 624, in run_instances
    return self.conn.run_instances(image_id, **kwargs)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/boto-2.31.1-py2.7.egg/boto/ec2/connection.py", line 961, in run_instances
    verb='POST')
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/boto-2.31.1-py2.7.egg/boto/connection.py", line 1164, in get_object
    response = self.make_request(action, params, path, verb)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/boto-2.31.1-py2.7.egg/boto/connection.py", line 1090, in make_request
    return self._mexe(http_request)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/boto-2.31.1-py2.7.egg/boto/connection.py", line 1003, in _mexe
    raise BotoServerError(response.status, response.reason, body)
BotoServerError: BotoServerError: 500 Internal Server Error
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InternalError</Code><Message>An internal error has occurred</Message></Error></Errors><RequestID>09fdda2a-c918-4970-856a-cb8bdd7e0336</RequestID></Response>`

**Comment by rezuma** [comment]
Hi,

I am having similar issues, in my case I am using the East Region which is
having a high level of API errors. AWS is reporting that on their list of
issues

http://status.aws.amazon.com/

Ramon
