### ISSUE TITLE
mount.nfs: Connection timed out

### ISSUE THREAD

**Issue by cancan101** [jtriley/StarCluster#540]
The master was likely busy at this point, but this is a crappy way for the startup to fail:

```
2015-07-06 14:48:56,736 PID: 21642 cli.py:284 - ERROR - error occurred in job (id=node053): remote command 'source /etc/profile && mount /home' failed with status 32:
mount.nfs: Connection timed out
Traceback (most recent call last):
  File "/home/ubuntu/Envs/starcluster/local/lib/python2.7/site-packages/starcluster/threadpool.py", line 48, in run
    job.run()
  File "/home/ubuntu/Envs/starcluster/local/lib/python2.7/site-packages/starcluster/threadpool.py", line 75, in run
    r = self.method(*self.args, **self.kwargs)
  File "/home/ubuntu/Envs/starcluster/local/lib/python2.7/site-packages/starcluster/node.py", line 766, in mount_nfs_shares
    self.ssh.execute('mount %s' % path)
  File "/home/ubuntu/Envs/starcluster/local/lib/python2.7/site-packages/starcluster/sshutils.py", line 589, in execute
    msg, command, exit_status, out_str)
RemoteCommandFailed: remote command 'source /etc/profile && mount /home' failed with status 32:
mount.nfs: Connection timed out
```

**Comment by cancan101** [comment]
This may be helped by: https://github.com/cancan101/StarCluster/commit/c2965063ea8b118761c42ba7c2b311d7df56937a. Also might want to add `noatime`.
