### ISSUE TITLE
Issue of using starcluster after installation

### ISSUE THREAD

**Issue by xuxie1031** [jtriley/StarCluster#555]
I tried manually install the 'StarCluster-0.95.6.tar.gz' by python2.7.
After the installation, I tried to type 'starcluster' in terminal, the error printouts:

:~$ starcluster 
Traceback (most recent call last):
  File "/usr/local/bin/starcluster", line 9, in <module>
    load_entry_point('StarCluster==0.95.6', 'console_scripts', 'starcluster')()
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.19-py2.7.egg/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.19-py2.7.egg/pkg_resources.py", line 2281, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.19-py2.7.egg/pkg_resources.py", line 1991, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/cli.py", line 32, in <module>
    from starcluster import config
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/config.py", line 25, in <module>
    from starcluster import cluster
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/cluster.py", line 33, in <module>
    from starcluster import deathrow
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/deathrow.py", line 24, in <module>
    from starcluster import clustersetup
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/clustersetup.py", line 24, in <module>
    from starcluster import threadpool
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.6-py2.7.egg/starcluster/threadpool.py", line 25, in <module>
    import workerpool
  File "/usr/local/lib/python2.7/dist-packages/workerpool-0.9.4-py2.7.egg/workerpool/**init**.py", line 29, in <module>
    from workerpool.pools import *
  File "/usr/local/lib/python2.7/dist-packages/workerpool-0.9.4-py2.7.egg/workerpool/pools.py", line 7, in <module>
    from six.moves import range
ImportError: cannot import name range

How to fix this problem? thx in advance.

**Comment by ghost** [comment]
I have the same issue.  Still no workaround that I have found.

**Comment by ghost** [comment]
Had some luck.  Tried installing elasticluster.  It must have "fixed" some references.  Then tried re-installing starcluster.  The import error went away.

**Comment by Milos** [comment]
Same issue with v. 0.95.6 on OS X El Capitan. 
Also, i couldn't even uninstall it with pip uninstall command. I get thrown Exception. Had to do it manually... I'm truly dispirited...

**Comment by Milos** [comment]
**UPDATE**:  `brew reinstall python` fixed the problem. After freshly installed python i installed it again and it worked.

**Comment by yj-yjh-yj** [comment]
The same problem here, solved after reinstalled python. Thanks @Milos
