### ISSUE TITLE
Exception on load balancer with 200+ spot requests

### ISSUE THREAD

**Issue by xanderdunn** [jtriley/StarCluster#567]
I ran this command: `starcluster loadbalance -m 300 -n 1 -a 240 -w 300 testcluster`

The cluster started with a master and a single spot instance node.  

I see this exception when it attempts to add 240 nodes: 

```
>>> Loading full job history
Execution hosts: 2
Queued jobs: 492
Oldest queued job: 2016-01-06 00:07:21+00:00
Avg job duration: 300 secs
Avg job wait time: 16 secs
Last cluster modification time: 2016-01-06 00:22:37+0000
>>> Queued jobs need more slots (492) than available (0)
>>> A job has been waiting for 1096 seconds longer than max: 300
*** WARNING - Adding 240 nodes at 2016-01-06 00:25:41.447050+00:00
>>> Launching node(s): node002, node003, node004, node005, node006, node007, node008, node009, node010, node011, node012, node013, node014, node015, node016, node017, node018, node019, node020, node021, node022, node023, node024, node025, node026, node027, node028, node029, node030, node031, node032, node033, node034, node035, node036, node037, node038, node039, node040, node041, node042, node043, node044, node045, node046, node047, node048, node049, node050, node051, node052, node053, node054, node055, node056, node057, node058, node059, node060, node061, node062, node063, node064, node065, node066, node067, node068, node069, node070, node071, node072, node073, node074, node075, node076, node077, node078, node079, node080, node081, node082, node083, node084, node085, node086, node087, node088, node089, node090, node091, node092, node093, node094, node095, node096, node097, node098, node099, node100, node101, node102, node103, node104, node105, node106, node107, node108, node109, node110, node111, node112, node113, node114, node115, node116, node117, node118, node119, node120, node121, node122, node123, node124, node125, node126, node127, node128, node129, node130, node131, node132, node133, node134, node135, node136, node137, node138, node139, node140, node141, node142, node143, node144, node145, node146, node147, node148, node149, node150, node151, node152, node153, node154, node155, node156, node157, node158, node159, node160, node161, node162, node163, node164, node165, node166, node167, node168, node169, node170, node171, node172, node173, node174, node175, node176, node177, node178, node179, node180, node181, node182, node183, node184, node185, node186, node187, node188, node189, node190, node191, node192, node193, node194, node195, node196, node197, node198, node199, node200, node201, node202, node203, node204, node205, node206, node207, node208, node209, node210, node211, node212, node213, node214, node215, node216, node217, node218, node219, node220, node221, node222, node223, node224, node225, node226, node227, node228, node229, node230, node231, node232, node233, node234, node235, node236, node237, node238, node239, node240, node241
SpotInstanceRequest:sir-037e4n1e
SpotInstanceRequest:sir-037awsd7
SpotInstanceRequest:sir-0379e2bt
SpotInstanceRequest:sir-0379hlkh
SpotInstanceRequest:sir-037e7ksx
SpotInstanceRequest:sir-037b3dkv
SpotInstanceRequest:sir-0377wd4t
SpotInstanceRequest:sir-0378vcvq
SpotInstanceRequest:sir-0378b4sp
SpotInstanceRequest:sir-037fdqhd
SpotInstanceRequest:sir-0379wjwp
SpotInstanceRequest:sir-037c0z1b
SpotInstanceRequest:sir-037d51nz
SpotInstanceRequest:sir-03792s4s
SpotInstanceRequest:sir-037eqlz1
SpotInstanceRequest:sir-0378lwzz
SpotInstanceRequest:sir-037dermp
SpotInstanceRequest:sir-037b3m92
SpotInstanceRequest:sir-0377z52f
SpotInstanceRequest:sir-037dgh5m
SpotInstanceRequest:sir-037fplle
SpotInstanceRequest:sir-03794f0p
SpotInstanceRequest:sir-037blj4j
SpotInstanceRequest:sir-0377ecxx
SpotInstanceRequest:sir-0377vqgj
SpotInstanceRequest:sir-037cb61x
SpotInstanceRequest:sir-03788lx8
SpotInstanceRequest:sir-037f6n1g
SpotInstanceRequest:sir-037bw8cf
SpotInstanceRequest:sir-037eq1he
SpotInstanceRequest:sir-037al7kw
SpotInstanceRequest:sir-037cg865
SpotInstanceRequest:sir-037ask9s
SpotInstanceRequest:sir-037a9bn0
SpotInstanceRequest:sir-037g64zm
SpotInstanceRequest:sir-0377tesr
SpotInstanceRequest:sir-037c329z
SpotInstanceRequest:sir-037a2gzj
SpotInstanceRequest:sir-037b515g
SpotInstanceRequest:sir-03798jh1
SpotInstanceRequest:sir-037dma3r
SpotInstanceRequest:sir-037h09rd
SpotInstanceRequest:sir-037ev7l8
SpotInstanceRequest:sir-037h6ewe
SpotInstanceRequest:sir-037ahxp0
SpotInstanceRequest:sir-037ftsrf
SpotInstanceRequest:sir-037a42gr
SpotInstanceRequest:sir-037fvspa
SpotInstanceRequest:sir-037f9j2n
SpotInstanceRequest:sir-0377vmnc
SpotInstanceRequest:sir-03780zff
SpotInstanceRequest:sir-0378cm7n
SpotInstanceRequest:sir-037a698m
SpotInstanceRequest:sir-037bwmdt
SpotInstanceRequest:sir-03798sgq
SpotInstanceRequest:sir-037f8jxt
SpotInstanceRequest:sir-0377h9q5
SpotInstanceRequest:sir-037gaxtf
SpotInstanceRequest:sir-03777pbh
SpotInstanceRequest:sir-0377q5d8
SpotInstanceRequest:sir-037gwmb4
SpotInstanceRequest:sir-03788ev7
SpotInstanceRequest:sir-037csl78
SpotInstanceRequest:sir-0378g4t9
SpotInstanceRequest:sir-0378x21a
SpotInstanceRequest:sir-0379bqpx
SpotInstanceRequest:sir-0377drmh
SpotInstanceRequest:sir-037bz2ap
SpotInstanceRequest:sir-0378w2wp
SpotInstanceRequest:sir-03780j3v
SpotInstanceRequest:sir-037913g4
SpotInstanceRequest:sir-037c7fhm
SpotInstanceRequest:sir-037cz3lj
SpotInstanceRequest:sir-037brt8x
SpotInstanceRequest:sir-037fbhm1
SpotInstanceRequest:sir-037cbm5w
SpotInstanceRequest:sir-037fkdje
SpotInstanceRequest:sir-037cgxc7
SpotInstanceRequest:sir-037g0d92
SpotInstanceRequest:sir-0379ngpl
SpotInstanceRequest:sir-037dk10j
SpotInstanceRequest:sir-0378hl3c
SpotInstanceRequest:sir-037ex304
SpotInstanceRequest:sir-037drhz6
SpotInstanceRequest:sir-0379k935
SpotInstanceRequest:sir-0377xlxk
SpotInstanceRequest:sir-0378lf64
SpotInstanceRequest:sir-0377hwj9
SpotInstanceRequest:sir-037avbpd
SpotInstanceRequest:sir-0379ejbq
SpotInstanceRequest:sir-037dt6r9
SpotInstanceRequest:sir-037dczt5
SpotInstanceRequest:sir-037ephh7
SpotInstanceRequest:sir-0377dt07
SpotInstanceRequest:sir-037ewd21
SpotInstanceRequest:sir-037c4x50
SpotInstanceRequest:sir-037988al
SpotInstanceRequest:sir-037b620w
SpotInstanceRequest:sir-037faved
SpotInstanceRequest:sir-037gxkjh
SpotInstanceRequest:sir-037dd73k
SpotInstanceRequest:sir-037dvm3c
SpotInstanceRequest:sir-0379rcd8
SpotInstanceRequest:sir-037b10h7
SpotInstanceRequest:sir-037ew53g
SpotInstanceRequest:sir-037glrkk
SpotInstanceRequest:sir-037af92m
SpotInstanceRequest:sir-0378sw2s
SpotInstanceRequest:sir-037entvt
SpotInstanceRequest:sir-0377dmqf
SpotInstanceRequest:sir-037eqrjf
SpotInstanceRequest:sir-037g0sqf
SpotInstanceRequest:sir-037gpjaf
SpotInstanceRequest:sir-03777q0n
SpotInstanceRequest:sir-037eanbp
SpotInstanceRequest:sir-037fm3xg
SpotInstanceRequest:sir-037gnv6q
SpotInstanceRequest:sir-037g78g4
SpotInstanceRequest:sir-037gf4p2
SpotInstanceRequest:sir-0378d1q5
SpotInstanceRequest:sir-037gp2mr
SpotInstanceRequest:sir-0378l2dn
SpotInstanceRequest:sir-037b8s7d
SpotInstanceRequest:sir-037c6ewr
SpotInstanceRequest:sir-037a84ns
SpotInstanceRequest:sir-0378jdna
SpotInstanceRequest:sir-0377nd0s
SpotInstanceRequest:sir-0377f5aw
SpotInstanceRequest:sir-037e349x
SpotInstanceRequest:sir-0377akdp
SpotInstanceRequest:sir-0377xd46
SpotInstanceRequest:sir-037b49l2
SpotInstanceRequest:sir-037h5r4g
SpotInstanceRequest:sir-037fm0le
SpotInstanceRequest:sir-037bp4pm
SpotInstanceRequest:sir-0379rq7f
SpotInstanceRequest:sir-03789qal
SpotInstanceRequest:sir-0377zhbw
SpotInstanceRequest:sir-037cge1k
SpotInstanceRequest:sir-037gxejx
SpotInstanceRequest:sir-037dwf4g
SpotInstanceRequest:sir-03784fj6
SpotInstanceRequest:sir-037ckvex
SpotInstanceRequest:sir-037ecqbw
SpotInstanceRequest:sir-037819sr
SpotInstanceRequest:sir-037ggjhp
SpotInstanceRequest:sir-037ea6tm
SpotInstanceRequest:sir-037d6xfa
SpotInstanceRequest:sir-03785w3a
SpotInstanceRequest:sir-03780s02
SpotInstanceRequest:sir-037d71g3
SpotInstanceRequest:sir-037a645j
SpotInstanceRequest:sir-0377l1t4
SpotInstanceRequest:sir-03781r7k
SpotInstanceRequest:sir-0377x3px
SpotInstanceRequest:sir-037c0p89
SpotInstanceRequest:sir-0379czl4
SpotInstanceRequest:sir-0378mvl9
SpotInstanceRequest:sir-037fj430
SpotInstanceRequest:sir-037cz1zt
SpotInstanceRequest:sir-037gk1gz
SpotInstanceRequest:sir-0379z0vp
SpotInstanceRequest:sir-037d4xlj
SpotInstanceRequest:sir-037bedeq
SpotInstanceRequest:sir-037fv1tl
SpotInstanceRequest:sir-037bn3e0
SpotInstanceRequest:sir-037b0kbw
SpotInstanceRequest:sir-037fmatz
SpotInstanceRequest:sir-037g2rm2
SpotInstanceRequest:sir-037ddxb2
SpotInstanceRequest:sir-03795r8q
SpotInstanceRequest:sir-037elf0f
SpotInstanceRequest:sir-037b4brj
SpotInstanceRequest:sir-0378k7d5
SpotInstanceRequest:sir-037h2v0t
SpotInstanceRequest:sir-037dske6
SpotInstanceRequest:sir-037bpr9k
SpotInstanceRequest:sir-0379sj43
SpotInstanceRequest:sir-037fref8
SpotInstanceRequest:sir-037a51rf
SpotInstanceRequest:sir-037geh87
SpotInstanceRequest:sir-0377wfbk
SpotInstanceRequest:sir-037cmqlf
SpotInstanceRequest:sir-037a7jc3
SpotInstanceRequest:sir-037a3vna
SpotInstanceRequest:sir-037amldb
SpotInstanceRequest:sir-037gdzkz
SpotInstanceRequest:sir-0379dw7b
SpotInstanceRequest:sir-037dx20a
SpotInstanceRequest:sir-0378kan2
SpotInstanceRequest:sir-037ds7qk
SpotInstanceRequest:sir-037f0phq
SpotInstanceRequest:sir-0377n4g1
SpotInstanceRequest:sir-037f31n7
SpotInstanceRequest:sir-0377ddnt
SpotInstanceRequest:sir-037et0bv
SpotInstanceRequest:sir-037f4fhp
SpotInstanceRequest:sir-037ed0sh
SpotInstanceRequest:sir-0378n5rv
SpotInstanceRequest:sir-037eref8
SpotInstanceRequest:sir-0378hhzs
SpotInstanceRequest:sir-0377v1cf
SpotInstanceRequest:sir-037fal6r
SpotInstanceRequest:sir-0377l81v
SpotInstanceRequest:sir-037ahwaj
SpotInstanceRequest:sir-037e0zjn
SpotInstanceRequest:sir-037d8jze
SpotInstanceRequest:sir-037amrfb
SpotInstanceRequest:sir-0378g1xa
SpotInstanceRequest:sir-037gsc2g
SpotInstanceRequest:sir-037dkl9h
SpotInstanceRequest:sir-03795cnf
SpotInstanceRequest:sir-037c05xt
SpotInstanceRequest:sir-037dcbcv
SpotInstanceRequest:sir-037gddmp
SpotInstanceRequest:sir-037b6sjj
SpotInstanceRequest:sir-037exznb
SpotInstanceRequest:sir-0378ld4j
SpotInstanceRequest:sir-037dkzk4
SpotInstanceRequest:sir-037dke75
SpotInstanceRequest:sir-037e2sej
SpotInstanceRequest:sir-037fvn3z
SpotInstanceRequest:sir-037gl5re
SpotInstanceRequest:sir-037823cn
SpotInstanceRequest:sir-03788z0m
SpotInstanceRequest:sir-037b8lls
SpotInstanceRequest:sir-037f46wl
SpotInstanceRequest:sir-037c8l1x
SpotInstanceRequest:sir-037drpv8
SpotInstanceRequest:sir-0379bvsv
SpotInstanceRequest:sir-0379q748
SpotInstanceRequest:sir-037dvtjm
SpotInstanceRequest:sir-0379sv6q
SpotInstanceRequest:sir-037h26cn
SpotInstanceRequest:sir-0379qj5a
SpotInstanceRequest:sir-037gf9x3
SpotInstanceRequest:sir-037ammrd
SpotInstanceRequest:sir-037elwlx
SpotInstanceRequest:sir-037bc2fv
SpotInstanceRequest:sir-037d7dp7
>>> Waiting for spot requests to propagate...
240/240 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
!!! ERROR - Failed to add new host
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/starcluster/balancers/sge/__init__.py", line 727, in _eval_add_node
    self._cluster.add_nodes(need_to_add)
  File "/usr/local/lib/python2.7/dist-packages/starcluster/cluster.py", line 1035, in add_nodes
    self.ec2.wait_for_propagation(spot_requests=resp)
  File "/usr/local/lib/python2.7/dist-packages/starcluster/awsutils.py", line 597, in wait_for_propagation
    max_retries=max_retries, interval=interval)
  File "/usr/local/lib/python2.7/dist-packages/starcluster/awsutils.py", line 562, in _wait_for_propagation
    reqs = fetch_func(filters=filters)
  File "/usr/local/lib/python2.7/dist-packages/starcluster/awsutils.py", line 776, in get_all_spot_requests
    filters=filters)
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 1340, in get_all_spot_instance_requests
    [('item', SpotInstanceRequest)], verb='POST')
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1186, in get_list
    raise self.ResponseError(response.status, response.reason, body)
EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>FilterLimitExceeded</Code><Message>The maximum number of filter values specified on a single call is 200</Message></Error></Errors><RequestID>5a8e16c4-3c6d-42b1-a14d-64bdb5e9ff0d</RequestID></Response>
>>> Sleeping...(looping again in 60 secs)

>>> Waiting for all nodes to come up...
>>> Waiting for all nodes to come up...
```

The `FilterLimitExceeded` seems to be returned from AWS, [shown here](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html).

I see someone on the mailing list who hit this same problem: http://star.mit.edu/cluster/mlarchives/2460.html

**Comment by xanderdunn** [comment]
I installed with `sudo -H pip install https://github.com/jtriley/StarCluster/archive/develop.zip`

**Comment by vasisht** [comment]
Adding the nodes in a streaming fashion should help resolve the error.

See https://github.com/jtriley/StarCluster/issues/581
