### ISSUE TITLE
test failure with pytest 2.8.7

### ISSUE THREAD

**Issue by opoplawski** [jtriley/StarCluster#573]
```
+ /usr/bin/python setup.py test
running test
running egg_info
writing requirements to StarCluster.egg-info/requires.txt
writing StarCluster.egg-info/PKG-INFO
writing top-level names to StarCluster.egg-info/top_level.txt
writing dependency_links to StarCluster.egg-info/dependency_links.txt
writing entry points to StarCluster.egg-info/entry_points.txt
reading manifest file 'StarCluster.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching 'requirements.txt'
writing manifest file 'StarCluster.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 165, in <module>
    **extra
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 159, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 140, in with_project_on_sys_path
    func()
  File "setup.py", line 59, in run_tests
    pm.consider_setuptools_entrypoints()
AttributeError: 'PytestPluginManager' object has no attribute 'consider_setuptools_entrypoints'
```

Then:

```
usage: setup.py [options] [file_or_dir] [file_or_dir] [...]
setup.py: error: unrecognized arguments: --clearcache
```

Patch:

```
diff -up StarCluster-0.95.6/pytest.ini.pytest StarCluster-0.95.6/pytest.ini
--- StarCluster-0.95.6/pytest.ini.pytest    2014-11-05 15:36:10.000000000 -0700
+++ StarCluster-0.95.6/pytest.ini   2016-02-07 16:58:44.211807979 -0700
@@ -1,2 +1,2 @@
 [pytest]
-addopts = starcluster -xvs -rs --pep8 --flakes --clearcache
+addopts = starcluster -xvs -rs --pep8 --flakes
diff -up StarCluster-0.95.6/setup.py.pytest StarCluster-0.95.6/setup.py
--- StarCluster-0.95.6/setup.py.pytest  2014-11-05 15:36:10.000000000 -0700
+++ StarCluster-0.95.6/setup.py 2016-02-07 16:49:07.193353590 -0700
@@ -52,11 +52,6 @@ try:
         def run_tests(self):
             # import here, cause outside the eggs aren't loaded
             import pytest
-            # Needed in order for pytest_cache to load properly
-            # Alternate fix: import pytest_cache and pass to pytest.main
-            import _pytest.config
-            pm = _pytest.config.get_plugin_manager()
-            pm.consider_setuptools_entrypoints()
             errno = pytest.main(self.test_args)
             sys.exit(errno)
```

Now have pep8 failure:

```
__________________________________ PEP8-check __________________________________
/builddir/build/BUILD/StarCluster-0.95.6/starcluster/progressbar.py:55:1: E402 module level import not at top of file
import sys
^
/builddir/build/BUILD/StarCluster-0.95.6/starcluster/progressbar.py:56:1: E402 module level import not at top of file
import time
^
/builddir/build/BUILD/StarCluster-0.95.6/starcluster/progressbar.py:57:1: E402 module level import not at top of file
from array import array
^
/builddir/build/BUILD/StarCluster-0.95.6/starcluster/progressbar.py:63:1: E402 module level import not at top of file
import signal
^
```

**Comment by opoplawski** [comment]
And:

```
__________________________ PEP8-check(ignoring E402) ___________________________
/builddir/build/BUILD/StarCluster-0.95.6/starcluster/utils.py:438:26: E241 multiple spaces after ','
    v = v2fhelper(v, "a",  version, 1)
                         ^
/builddir/build/BUILD/StarCluster-0.95.6/starcluster/utils.py:439:26: E241 multiple spaces after ','
    v = v2fhelper(v, "b",  version, 2)
                         ^
/home/orion/fedora/StarCluster/StarCluster-0.95.6/starcluster/commands/removenode.py:67:41: E241 multiple spaces after ','
                          default=False,  help="Terminate node regardless "
                                        ^
/builddir/build/BUILD/StarCluster-0.95.6/starcluster/plugins/ipcluster.py:189:21: W503 line break before binary operator
                    + json_filename)
                    ^
```
