### ISSUE TITLE
cannot run `starcluster --help`

### ISSUE THREAD

**Issue by floswald** [jtriley/StarCluster#577]
hi
i posted this to the mailing list, but couldn't get through it seems. my problem is

```
➜  ~ starcluster --help
Traceback (most recent call last):
  File "/usr/local/bin/starcluster", line 9, in <module>
    load_entry_point('StarCluster==0.95.6', 'console_scripts', 'starcluster')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Library/Python/2.7/site-packages/StarCluster-0.95.6-py2.7.egg/starcluster/cli.py", line 32, in <module>
    from starcluster import config
  File "/Library/Python/2.7/site-packages/StarCluster-0.95.6-py2.7.egg/starcluster/config.py", line 25, in <module>
    from starcluster import cluster
  File "/Library/Python/2.7/site-packages/StarCluster-0.95.6-py2.7.egg/starcluster/cluster.py", line 33, in <module>
    from starcluster import deathrow
  File "/Library/Python/2.7/site-packages/StarCluster-0.95.6-py2.7.egg/starcluster/deathrow.py", line 24, in <module>
    from starcluster import clustersetup
  File "/Library/Python/2.7/site-packages/StarCluster-0.95.6-py2.7.egg/starcluster/clustersetup.py", line 24, in <module>
    from starcluster import threadpool
  File "/Library/Python/2.7/site-packages/StarCluster-0.95.6-py2.7.egg/starcluster/threadpool.py", line 25, in <module>
    import workerpool
  File "/Library/Python/2.7/site-packages/workerpool-0.9.4-py2.7.egg/workerpool/__init__.py", line 29, in <module>
    from workerpool.pools import *
  File "/Library/Python/2.7/site-packages/workerpool-0.9.4-py2.7.egg/workerpool/pools.py", line 8, in <module>
    from six.moves.queue import Queue
ImportError: No module named queue
➜  ~ which python
/usr/bin/python
➜  ~ python --version
Python 2.7.10
➜  ~ python
Python 2.7.10 (default, Oct 23 2015, 18:05:06) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from six.moves import queue
>>> queue
<module 'Queue' from '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Queue.pyc'>
>>> exit()
```

**Comment by machbio** [comment]
@floswald  - check the version of workerpool package you are using..  see the requirements for starcluster here - https://github.com/jtriley/StarCluster/blob/develop/requirements.txt

**Comment by floswald** [comment]
thanks. I found out that the version of python that ships with yosemite does not work. one needs home-brew python for this.

**Comment by ernestatistics** [comment]
Hi floswald, I hd the same issue so I installed Python 3.5.

After you installed an updated version of Python how did you install Starcluster? I have the probem that Starcluster still wants to use my older version of Python.

**Comment by henriquefreitas** [comment]
This did it for me: `pip install six --user --upgrade --ignore-installed`
