### ISSUE TITLE
Issue with running commands in starcluster README

### ISSUE THREAD

**Issue by kk663** [jtriley/StarCluster#585]
I run all the steps in the starcluster README up to this step:
starcluster start mycluster

I get the error below on a Mac. Could you please tell me what is causing the error?

error occurred in job (id=node001): 'EntryPoint' object has no attribute 'resolve'
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/StarCluster-0.95.6-py2.7.egg/starcluster/threadpool.py", line 48, in run
    job.run()
  File "/Library/Python/2.7/site-packages/StarCluster-0.95.6-py2.7.egg/starcluster/threadpool.py", line 75, in run
    r = self.method(_self.args, *_self.kwargs)
  File "/Library/Python/2.7/site-packages/StarCluster-0.95.6-py2.7.egg/starcluster/cluster.py", line 1429, in <lambda>
    self.pool.map(lambda n: n.wait(interval=self.refresh_interval), nodes,
  File "/Library/Python/2.7/site-packages/StarCluster-0.95.6-py2.7.egg/starcluster/node.py", line 1019, in wait
    while not self.is_up():
  File "/Library/Python/2.7/site-packages/StarCluster-0.95.6-py2.7.egg/starcluster/node.py", line 1025, in is_up
    if not self.is_ssh_up():
  File "/Library/Python/2.7/site-packages/StarCluster-0.95.6-py2.7.egg/starcluster/node.py", line 1010, in is_ssh_up
    return self.ssh.transport is not None
  File "/Library/Python/2.7/site-packages/StarCluster-0.95.6-py2.7.egg/starcluster/node.py", line 1070, in ssh
    private_key=self.key_location)
  File "/Library/Python/2.7/site-packages/StarCluster-0.95.6-py2.7.egg/starcluster/sshutils.py", line 78, in **init**
    self._pkey = self.load_private_key(private_key, private_key_pass)
  File "/Library/Python/2.7/site-packages/StarCluster-0.95.6-py2.7.egg/starcluster/sshutils.py", line 89, in load_private_key
    pkey = self._load_rsa_key(private_key, private_key_pass)
  File "/Library/Python/2.7/site-packages/StarCluster-0.95.6-py2.7.egg/starcluster/sshutils.py", line 184, in _load_rsa_key
    passphrase=private_key_pass)
  File "/Library/Python/2.7/site-packages/StarCluster-0.95.6-py2.7.egg/starcluster/sshutils.py", line 816, in get_rsa_key
    password=passphrase)
  File "build/bdist.macosx-10.11-intel/egg/paramiko/pkey.py", line 217, in from_private_key
    key = cls(file_obj=file_obj, password=password)
  File "build/bdist.macosx-10.11-intel/egg/paramiko/rsakey.py", line 42, in __init__
    self._from_private_key(file_obj, password)
  File "build/bdist.macosx-10.11-intel/egg/paramiko/rsakey.py", line 168, in _from_private_key
    self._decode_key(data)
  File "build/bdist.macosx-10.11-intel/egg/paramiko/rsakey.py", line 173, in _decode_key
    data, password=None, backend=default_backend()
  File "/Library/Python/2.7/site-packages/cryptography-1.4-py2.7-macosx-10.11-intel.egg/cryptography/hazmat/backends/__init__.py", line 35, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/Library/Python/2.7/site-packages/cryptography-1.4-py2.7-macosx-10.11-intel.egg/cryptography/hazmat/backends/__init__.py", line 22, in _available_backends
    "cryptography.backends"
AttributeError: 'EntryPoint' object has no attribute 'resolve'

**Comment by vttrifonov** [comment]
same here. any solution to this? 

surprisingly, running (??) 

python -v /path-to-starcluster/starcluster start mycluster 

works every now and then (i was trying to see what is happening in python and it magically went through). not always though...

**Comment by vttrifonov** [comment]
It went down to upgrading Python packages in /System and I could not figure out how to do it  nicely (I am on Mac OS X El Capitain). So I ditched the default Mac OS X python installation and went with a new one from MacPorts which solved the problem.

**Comment by sanghamd** [comment]
I am having this same error in mac yosemite. Can you tell me how you exactly upgraded the python packages in mac?

**Comment by vasisht** [comment]
You would just need to upgrade setuptools. 
`sudo pip install -U setuptools`
