### ISSUE TITLE
AttributeError when running createvolume

### ISSUE THREAD

**Issue by seibert** [jtriley/StarCluster#60]
When running starcluster createvolume, this traceback appears at the end, after the volume appears to have been created successfully:

**\* WARNING - There are still volume hosts running: i-0de6f06e
**\* WARNING - Run 'starcluster terminate volumecreator' to terminate _all_ volume host instances once they're no longer needed
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/StarCluster-0.92.1-py2.7.egg/starcluster/cli.py", line 252, in main
    sc.execute(args)
  File "/Library/Python/2.7/site-packages/StarCluster-0.92.1-py2.7.egg/starcluster/commands/createvolume.py", line 135, in execute
    vc.create(size, zone, name=self.opts.name, tags=self.opts.tags)
  File "<string>", line 2, in create
  File "/Library/Python/2.7/site-packages/StarCluster-0.92.1-py2.7.egg/starcluster/utils.py", line 86, in wrap_f
    res = func(_arg, *_kargs)
  File "/Library/Python/2.7/site-packages/StarCluster-0.92.1-py2.7.egg/starcluster/volume.py", line 261, in create
    self.log.error("failed to create new volume")
AttributeError: 'VolumeCreator' object has no attribute 'log'

**Comment by jtriley** [comment]
Thanks for reporting, this is a stupid bug that will be fixed momentarily. Should be just 'log' not 'self.log'....
