### ISSUE TITLE
403 Error when creating security groups.

### ISSUE THREAD

**Issue by remyschwab** [jtriley/StarCluster#600]
If I try to run: starcluster start test, I get a 403 error: 

Using default cluster template: smallcluster
Validating cluster template settings...
Cluster template settings are valid
Starting cluster...
Launching a 2-node cluster...
Creating security group @sc-test...
!!! ERROR - UnauthorizedOperation: You are not authorized to perform this operation.

I was previously not permitted to create security groups but have changed those permissions and have tested that by launching a single instance with a security group that I made. Do you have any advice for me? Thanks in advance.

**Comment by nathanieldchu** [comment]
I've also run into this issue. I'll post a little more about the error I receive here. Like remyschwab, my account being used in the config file does have permissions to create security groups.

>>> Validating cluster template settings...
>>> Cluster template settings are valid
>>> Starting cluster...
>>> Launching a 10-node cluster...
>>> Launching master node (ami: ami-765b3e1f, type: m1.large)...
>>> Creating security group @sc-sf_test_cluster...
!!! ERROR - UnauthorizedOperation: You are not authorized to perform this operation.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/starcluster/cli.py", line 274, in main
    sc.execute(args)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/starcluster/commands/start.py", line 244, in execute
    validate_running=validate_running)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/starcluster/cluster.py", line 1628, in start
    return self._start(create=create, create_only=create_only)
  File "<decorator-gen-18>", line 2, in _start
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/starcluster/utils.py", line 112, in wrap_f
    res = func(*arg, **kargs)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/starcluster/cluster.py", line 1643, in _start
    self.create_cluster()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/starcluster/cluster.py", line 1161, in create_cluster
    self._create_spot_cluster()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/starcluster/cluster.py", line 1217, in _create_spot_cluster
    force_flat=force_flat)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/starcluster/cluster.py", line 894, in create_node
    spot_bid=spot_bid, force_flat=force_flat)[0]
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/starcluster/cluster.py", line 926, in create_nodes
    cluster_sg = self.cluster_group.name
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/starcluster/cluster.py", line 655, in cluster_group
    vpc_id=vpc_id)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/starcluster/awsutils.py", line 296, in create_group
    sg = self.conn.create_security_group(name, description, vpc_id=vpc_id)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/boto/ec2/connection.py", line 3003, in create_security_group
    SecurityGroup, verb='POST')
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/boto/connection.py", line 1208, in get_object
    raise self.ResponseError(response.status, response.reason, body)
EC2ResponseError: EC2ResponseError: 403 Forbidden
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>UnauthorizedOperation</Code><Message>You are not authorized to perform this operation.</Message></Error></Errors><RequestID>5bc119e0-84cf-4c4e-8372-0aa445c2c728</RequestID></Response>

I'm trying to dig into what else might be generating this error, but haven't found it yet. This error is on starcluster v. 0.95.6 running on an ubuntu AWS instance.
